"""OCSF 1.5.0 enumerations."""

from __future__ import annotations

import sys
from typing import Any

__all__ = [
    "AccountChangeActivityId",
    "AccountChangeCategoryUid",
    "AccountChangeClassUid",
    "AccountChangeSeverityId",
    "AccountChangeStatusId",
    "AccountTypeId",
    "AdminGroupQueryActivityId",
    "AdminGroupQueryCategoryUid",
    "AdminGroupQueryClassUid",
    "AdminGroupQueryQueryResultId",
    "AdminGroupQuerySeverityId",
    "AdminGroupQueryStatusId",
    "AdvisoryInstallStateId",
    "AffectedPackageTypeId",
    "AgentTypeId",
    "AirborneBroadcastActivityActivityId",
    "AirborneBroadcastActivityCategoryUid",
    "AirborneBroadcastActivityClassUid",
    "AirborneBroadcastActivitySeverityId",
    "AirborneBroadcastActivityStatusId",
    "AnalyticTypeId",
    "ApiActivityActivityId",
    "ApiActivityCategoryUid",
    "ApiActivityClassUid",
    "ApiActivitySeverityId",
    "ApiActivityStatusId",
    "ApplicationActivityId",
    "ApplicationCategoryUid",
    "ApplicationClassUid",
    "ApplicationErrorActivityId",
    "ApplicationErrorCategoryUid",
    "ApplicationErrorClassUid",
    "ApplicationErrorSeverityId",
    "ApplicationErrorStatusId",
    "ApplicationLifecycleActivityId",
    "ApplicationLifecycleCategoryUid",
    "ApplicationLifecycleClassUid",
    "ApplicationLifecycleSeverityId",
    "ApplicationLifecycleStatusId",
    "ApplicationRiskLevelId",
    "ApplicationSecurityPostureFindingActivityId",
    "ApplicationSecurityPostureFindingCategoryUid",
    "ApplicationSecurityPostureFindingClassUid",
    "ApplicationSecurityPostureFindingConfidenceId",
    "ApplicationSecurityPostureFindingSeverityId",
    "ApplicationSecurityPostureFindingStatusId",
    "ApplicationSeverityId",
    "ApplicationStatusId",
    "AuthFactorFactorTypeId",
    "AuthenticationActivityId",
    "AuthenticationAuthProtocolId",
    "AuthenticationCategoryUid",
    "AuthenticationClassUid",
    "AuthenticationLogonTypeId",
    "AuthenticationSeverityId",
    "AuthenticationStatusId",
    "AuthenticationTokenTypeId",
    "AuthorizeSessionActivityId",
    "AuthorizeSessionCategoryUid",
    "AuthorizeSessionClassUid",
    "AuthorizeSessionSeverityId",
    "AuthorizeSessionStatusId",
    "BaseEventActivityId",
    "BaseEventCategoryUid",
    "BaseEventClassUid",
    "BaseEventSeverityId",
    "BaseEventStatusId",
    "CheckSeverityId",
    "CheckStatusId",
    "CloudResourcesInventoryInfoActivityId",
    "CloudResourcesInventoryInfoCategoryUid",
    "CloudResourcesInventoryInfoClassUid",
    "CloudResourcesInventoryInfoSeverityId",
    "CloudResourcesInventoryInfoStatusId",
    "ComplianceFindingActivityId",
    "ComplianceFindingCategoryUid",
    "ComplianceFindingClassUid",
    "ComplianceFindingConfidenceId",
    "ComplianceFindingSeverityId",
    "ComplianceFindingStatusId",
    "ComplianceStatusId",
    "ConfigStateActivityId",
    "ConfigStateCategoryUid",
    "ConfigStateClassUid",
    "ConfigStateSeverityId",
    "ConfigStateStatusId",
    "CvssDepth",
    "DataClassificationCategoryId",
    "DataClassificationConfidentialityId",
    "DataClassificationStatusId",
    "DataSecurityCategoryId",
    "DataSecurityConfidentialityId",
    "DataSecurityDataLifecycleStateId",
    "DataSecurityDetectionSystemId",
    "DataSecurityFindingActivityId",
    "DataSecurityFindingCategoryUid",
    "DataSecurityFindingClassUid",
    "DataSecurityFindingConfidenceId",
    "DataSecurityFindingImpactId",
    "DataSecurityFindingRiskLevelId",
    "DataSecurityFindingSeverityId",
    "DataSecurityFindingStatusId",
    "DataSecurityStatusId",
    "DatabaseTypeId",
    "DatabucketTypeId",
    "DatastoreActivityActivityId",
    "DatastoreActivityCategoryUid",
    "DatastoreActivityClassUid",
    "DatastoreActivitySeverityId",
    "DatastoreActivityStatusId",
    "DatastoreActivityTypeId",
    "DetectionFindingActivityId",
    "DetectionFindingCategoryUid",
    "DetectionFindingClassUid",
    "DetectionFindingConfidenceId",
    "DetectionFindingImpactId",
    "DetectionFindingRiskLevelId",
    "DetectionFindingSeverityId",
    "DetectionFindingStatusId",
    "DeviceConfigStateChangeActivityId",
    "DeviceConfigStateChangeCategoryUid",
    "DeviceConfigStateChangeClassUid",
    "DeviceConfigStateChangePrevSecurityLevelId",
    "DeviceConfigStateChangeSecurityLevelId",
    "DeviceConfigStateChangeSeverityId",
    "DeviceConfigStateChangeStateId",
    "DeviceConfigStateChangeStatusId",
    "DeviceHwInfoCpuArchitectureId",
    "DeviceRiskLevelId",
    "DeviceTypeId",
    "DhcpActivityActivityId",
    "DhcpActivityCategoryUid",
    "DhcpActivityClassUid",
    "DhcpActivitySeverityId",
    "DhcpActivityStatusId",
    "DigitalSignatureAlgorithmId",
    "DigitalSignatureStateId",
    "DiscoveryActivityId",
    "DiscoveryCategoryUid",
    "DiscoveryClassUid",
    "DiscoveryResultActivityId",
    "DiscoveryResultCategoryUid",
    "DiscoveryResultClassUid",
    "DiscoveryResultQueryResultId",
    "DiscoveryResultSeverityId",
    "DiscoveryResultStatusId",
    "DiscoverySeverityId",
    "DiscoveryStatusId",
    "DnsActivityActivityId",
    "DnsActivityCategoryUid",
    "DnsActivityClassUid",
    "DnsActivityRcodeId",
    "DnsActivitySeverityId",
    "DnsActivityStatusId",
    "DnsAnswerFlagIds",
    "DnsQueryOpcodeId",
    "DomainContactTypeId",
    "DroneFlightsActivityActivityId",
    "DroneFlightsActivityAuthProtocolId",
    "DroneFlightsActivityCategoryUid",
    "DroneFlightsActivityClassUid",
    "DroneFlightsActivitySeverityId",
    "DroneFlightsActivityStatusId",
    "EmailActivityActivityId",
    "EmailActivityCategoryUid",
    "EmailActivityClassUid",
    "EmailActivityDirectionId",
    "EmailActivitySeverityId",
    "EmailActivityStatusId",
    "EmailFileActivityActivityId",
    "EmailFileActivityCategoryUid",
    "EmailFileActivityClassUid",
    "EmailFileActivitySeverityId",
    "EmailFileActivityStatusId",
    "EmailUrlActivityActivityId",
    "EmailUrlActivityCategoryUid",
    "EmailUrlActivityClassUid",
    "EmailUrlActivitySeverityId",
    "EmailUrlActivityStatusId",
    "EncryptionDetailsAlgorithmId",
    "EndpointTypeId",
    "EntityManagementActivityId",
    "EntityManagementCategoryUid",
    "EntityManagementClassUid",
    "EntityManagementSeverityId",
    "EntityManagementStatusId",
    "EventLogActvityActivityId",
    "EventLogActvityCategoryUid",
    "EventLogActvityClassUid",
    "EventLogActvityLogTypeId",
    "EventLogActvitySeverityId",
    "EventLogActvityStatusId",
    "EvidenceInfoActivityId",
    "EvidenceInfoCategoryUid",
    "EvidenceInfoClassUid",
    "EvidenceInfoQueryResultId",
    "EvidenceInfoSeverityId",
    "EvidenceInfoStatusId",
    "EvidencesVerdictId",
    "FileActivityActivityId",
    "FileActivityCategoryUid",
    "FileActivityClassUid",
    "FileActivitySeverityId",
    "FileActivityStatusId",
    "FileConfidentialityId",
    "FileDriveTypeId",
    "FileHostingActivityId",
    "FileHostingCategoryUid",
    "FileHostingClassUid",
    "FileHostingSeverityId",
    "FileHostingShareTypeId",
    "FileHostingStatusId",
    "FileQueryActivityId",
    "FileQueryCategoryUid",
    "FileQueryClassUid",
    "FileQueryQueryResultId",
    "FileQuerySeverityId",
    "FileQueryStatusId",
    "FileRemediationActivityActivityId",
    "FileRemediationActivityCategoryUid",
    "FileRemediationActivityClassUid",
    "FileRemediationActivitySeverityId",
    "FileRemediationActivityStatusId",
    "FileTypeId",
    "FindingActivityId",
    "FindingCategoryUid",
    "FindingClassUid",
    "FindingConfidenceId",
    "FindingSeverityId",
    "FindingStatusId",
    "FingerprintAlgorithmId",
    "FolderQueryActivityId",
    "FolderQueryCategoryUid",
    "FolderQueryClassUid",
    "FolderQueryQueryResultId",
    "FolderQuerySeverityId",
    "FolderQueryStatusId",
    "FtpActivityActivityId",
    "FtpActivityCategoryUid",
    "FtpActivityClassUid",
    "FtpActivitySeverityId",
    "FtpActivityStatusId",
    "GraphQueryLanguageId",
    "GroupManagementActivityId",
    "GroupManagementCategoryUid",
    "GroupManagementClassUid",
    "GroupManagementSeverityId",
    "GroupManagementStatusId",
    "HttpActivityActivityId",
    "HttpActivityCategoryUid",
    "HttpActivityClassUid",
    "HttpActivitySeverityId",
    "HttpActivityStatusId",
    "HttpRequestHttpMethod",
    "IamActivityId",
    "IamCategoryUid",
    "IamClassUid",
    "IamSeverityId",
    "IamStatusId",
    "IdpStateId",
    "IncidentFindingActivityId",
    "IncidentFindingCategoryUid",
    "IncidentFindingClassUid",
    "IncidentFindingConfidenceId",
    "IncidentFindingImpactId",
    "IncidentFindingPriorityId",
    "IncidentFindingSeverityId",
    "IncidentFindingStatusId",
    "IncidentFindingVerdictId",
    "InventoryInfoActivityId",
    "InventoryInfoCategoryUid",
    "InventoryInfoClassUid",
    "InventoryInfoSeverityId",
    "InventoryInfoStatusId",
    "Ja4FingerprintTypeId",
    "JobQueryActivityId",
    "JobQueryCategoryUid",
    "JobQueryClassUid",
    "JobQueryQueryResultId",
    "JobQuerySeverityId",
    "JobQueryStatusId",
    "JobRunStateId",
    "KbArticleInstallStateId",
    "KernelActivityActivityId",
    "KernelActivityCategoryUid",
    "KernelActivityClassUid",
    "KernelActivitySeverityId",
    "KernelActivityStatusId",
    "KernelExtensionActivityActivityId",
    "KernelExtensionActivityCategoryUid",
    "KernelExtensionActivityClassUid",
    "KernelExtensionActivitySeverityId",
    "KernelExtensionActivityStatusId",
    "KernelObjectQueryActivityId",
    "KernelObjectQueryCategoryUid",
    "KernelObjectQueryClassUid",
    "KernelObjectQueryQueryResultId",
    "KernelObjectQuerySeverityId",
    "KernelObjectQueryStatusId",
    "KernelTypeId",
    "KillChainPhasePhaseId",
    "MalwareClassificationIds",
    "MalwareScanInfoTypeId",
    "MalwareSeverityId",
    "ManagedEntityTypeId",
    "MemoryActivityActivityId",
    "MemoryActivityCategoryUid",
    "MemoryActivityClassUid",
    "MemoryActivitySeverityId",
    "MemoryActivityStatusId",
    "ModuleActivityActivityId",
    "ModuleActivityCategoryUid",
    "ModuleActivityClassUid",
    "ModuleActivitySeverityId",
    "ModuleActivityStatusId",
    "ModuleLoadTypeId",
    "ModuleQueryActivityId",
    "ModuleQueryCategoryUid",
    "ModuleQueryClassUid",
    "ModuleQueryQueryResultId",
    "ModuleQuerySeverityId",
    "ModuleQueryStatusId",
    "NetworkActivityActivityId",
    "NetworkActivityCategoryUid",
    "NetworkActivityClassUid",
    "NetworkActivityId",
    "NetworkActivitySeverityId",
    "NetworkActivityStatusId",
    "NetworkCategoryUid",
    "NetworkClassUid",
    "NetworkConnectionInfoBoundaryId",
    "NetworkConnectionInfoDirectionId",
    "NetworkConnectionInfoProtocolVerId",
    "NetworkConnectionQueryActivityId",
    "NetworkConnectionQueryCategoryUid",
    "NetworkConnectionQueryClassUid",
    "NetworkConnectionQueryQueryResultId",
    "NetworkConnectionQuerySeverityId",
    "NetworkConnectionQueryStateId",
    "NetworkConnectionQueryStatusId",
    "NetworkEndpointTypeId",
    "NetworkFileActivityActivityId",
    "NetworkFileActivityCategoryUid",
    "NetworkFileActivityClassUid",
    "NetworkFileActivitySeverityId",
    "NetworkFileActivityStatusId",
    "NetworkInterfaceTypeId",
    "NetworkProxyTypeId",
    "NetworkRemediationActivityActivityId",
    "NetworkRemediationActivityCategoryUid",
    "NetworkRemediationActivityClassUid",
    "NetworkRemediationActivitySeverityId",
    "NetworkRemediationActivityStatusId",
    "NetworkSeverityId",
    "NetworkStatusId",
    "NetworksQueryActivityId",
    "NetworksQueryCategoryUid",
    "NetworksQueryClassUid",
    "NetworksQueryQueryResultId",
    "NetworksQuerySeverityId",
    "NetworksQueryStatusId",
    "NtpActivityActivityId",
    "NtpActivityCategoryUid",
    "NtpActivityClassUid",
    "NtpActivitySeverityId",
    "NtpActivityStatusId",
    "NtpActivityStratumId",
    "ObservableTypeId",
    "OsTypeId",
    "OsintConfidenceId",
    "OsintDetectionPatternTypeId",
    "OsintInventoryInfoActivityId",
    "OsintInventoryInfoCategoryUid",
    "OsintInventoryInfoClassUid",
    "OsintInventoryInfoSeverityId",
    "OsintInventoryInfoStatusId",
    "OsintSeverityId",
    "OsintTlp",
    "OsintTypeId",
    "PackageTypeId",
    "PatchStateActivityId",
    "PatchStateCategoryUid",
    "PatchStateClassUid",
    "PatchStateSeverityId",
    "PatchStateStatusId",
    "PeripheralDeviceQueryActivityId",
    "PeripheralDeviceQueryCategoryUid",
    "PeripheralDeviceQueryClassUid",
    "PeripheralDeviceQueryQueryResultId",
    "PeripheralDeviceQuerySeverityId",
    "PeripheralDeviceQueryStatusId",
    "ProcessActivityActivityId",
    "ProcessActivityCategoryUid",
    "ProcessActivityClassUid",
    "ProcessActivityInjectionTypeId",
    "ProcessActivitySeverityId",
    "ProcessActivityStatusId",
    "ProcessIntegrityId",
    "ProcessQueryActivityId",
    "ProcessQueryCategoryUid",
    "ProcessQueryClassUid",
    "ProcessQueryQueryResultId",
    "ProcessQuerySeverityId",
    "ProcessQueryStatusId",
    "ProcessRemediationActivityActivityId",
    "ProcessRemediationActivityCategoryUid",
    "ProcessRemediationActivityClassUid",
    "ProcessRemediationActivitySeverityId",
    "ProcessRemediationActivityStatusId",
    "QueryEvidenceQueryTypeId",
    "QueryEvidenceTcpStateId",
    "RdpActivityActivityId",
    "RdpActivityCategoryUid",
    "RdpActivityClassUid",
    "RdpActivitySeverityId",
    "RdpActivityStatusId",
    "RelatedEventSeverityId",
    "RemediationActivityActivityId",
    "RemediationActivityCategoryUid",
    "RemediationActivityClassUid",
    "RemediationActivitySeverityId",
    "RemediationActivityStatusId",
    "ReputationScoreId",
    "SbomTypeId",
    "ScanActivityActivityId",
    "ScanActivityCategoryUid",
    "ScanActivityClassUid",
    "ScanActivitySeverityId",
    "ScanActivityStatusId",
    "ScanTypeId",
    "ScheduledJobActivityActivityId",
    "ScheduledJobActivityCategoryUid",
    "ScheduledJobActivityClassUid",
    "ScheduledJobActivitySeverityId",
    "ScheduledJobActivityStatusId",
    "ScimAuthProtocolId",
    "ScimStateId",
    "ScriptActivityActivityId",
    "ScriptActivityCategoryUid",
    "ScriptActivityClassUid",
    "ScriptActivitySeverityId",
    "ScriptActivityStatusId",
    "ScriptTypeId",
    "SecurityFindingActivityId",
    "SecurityFindingCategoryUid",
    "SecurityFindingClassUid",
    "SecurityFindingConfidenceId",
    "SecurityFindingImpactId",
    "SecurityFindingRiskLevelId",
    "SecurityFindingSeverityId",
    "SecurityFindingStateId",
    "SecurityFindingStatusId",
    "SecurityStateStateId",
    "ServiceQueryActivityId",
    "ServiceQueryCategoryUid",
    "ServiceQueryClassUid",
    "ServiceQueryQueryResultId",
    "ServiceQuerySeverityId",
    "ServiceQueryStatusId",
    "SessionQueryActivityId",
    "SessionQueryCategoryUid",
    "SessionQueryClassUid",
    "SessionQueryQueryResultId",
    "SessionQuerySeverityId",
    "SessionQueryStatusId",
    "SmbActivityActivityId",
    "SmbActivityCategoryUid",
    "SmbActivityClassUid",
    "SmbActivitySeverityId",
    "SmbActivityShareTypeId",
    "SmbActivityStatusId",
    "SoftwareComponentRelationshipId",
    "SoftwareComponentTypeId",
    "SoftwareInfoActivityId",
    "SoftwareInfoCategoryUid",
    "SoftwareInfoClassUid",
    "SoftwareInfoSeverityId",
    "SoftwareInfoStatusId",
    "SshActivityActivityId",
    "SshActivityAuthTypeId",
    "SshActivityCategoryUid",
    "SshActivityClassUid",
    "SshActivitySeverityId",
    "SshActivityStatusId",
    "SsoAuthProtocolId",
    "StartupItemQueryActivityId",
    "StartupItemQueryCategoryUid",
    "StartupItemQueryClassUid",
    "StartupItemQueryQueryResultId",
    "StartupItemQuerySeverityId",
    "StartupItemQueryStatusId",
    "StartupItemRunModeIds",
    "StartupItemRunStateId",
    "StartupItemStartTypeId",
    "StartupItemTypeId",
    "SystemActivityId",
    "SystemCategoryUid",
    "SystemClassUid",
    "SystemSeverityId",
    "SystemStatusId",
    "ThreatActorTypeId",
    "TicketStatusId",
    "TicketTypeId",
    "TimespanTypeId",
    "TlsExtensionTypeId",
    "TunnelActivityActivityId",
    "TunnelActivityCategoryUid",
    "TunnelActivityClassUid",
    "TunnelActivitySeverityId",
    "TunnelActivityStatusId",
    "TunnelActivityTunnelTypeId",
    "UnmannedAerialSystemTypeId",
    "UnmannedSystemOperatingAreaTypeId",
    "UnmannedSystemsActivityId",
    "UnmannedSystemsCategoryUid",
    "UnmannedSystemsClassUid",
    "UnmannedSystemsSeverityId",
    "UnmannedSystemsStatusId",
    "UrlCategoryIds",
    "UserAccessActivityId",
    "UserAccessCategoryUid",
    "UserAccessClassUid",
    "UserAccessSeverityId",
    "UserAccessStatusId",
    "UserInventoryActivityId",
    "UserInventoryCategoryUid",
    "UserInventoryClassUid",
    "UserInventorySeverityId",
    "UserInventoryStatusId",
    "UserQueryActivityId",
    "UserQueryCategoryUid",
    "UserQueryClassUid",
    "UserQueryQueryResultId",
    "UserQuerySeverityId",
    "UserQueryStatusId",
    "UserRiskLevelId",
    "UserTypeId",
    "VendorAttributesSeverityId",
    "VulnerabilityFindingActivityId",
    "VulnerabilityFindingCategoryUid",
    "VulnerabilityFindingClassUid",
    "VulnerabilityFindingConfidenceId",
    "VulnerabilityFindingSeverityId",
    "VulnerabilityFindingStatusId",
    "VulnerabilityFixCoverageId",
    "WebResourceAccessActivityActivityId",
    "WebResourceAccessActivityCategoryUid",
    "WebResourceAccessActivityClassUid",
    "WebResourceAccessActivitySeverityId",
    "WebResourceAccessActivityStatusId",
    "WebResourcesActivityActivityId",
    "WebResourcesActivityCategoryUid",
    "WebResourcesActivityClassUid",
    "WebResourcesActivitySeverityId",
    "WebResourcesActivityStatusId",
    "WhoisDnssecStatusId",
]

# Mapping of class names to their module file names
_MODULE_MAP = {
    "AccountChangeActivityId": "account_change_activity_id",
    "AccountChangeCategoryUid": "account_change_category_uid",
    "AccountChangeClassUid": "account_change_class_uid",
    "AccountChangeSeverityId": "account_change_severity_id",
    "AccountChangeStatusId": "account_change_status_id",
    "AccountTypeId": "account_type_id",
    "AdminGroupQueryActivityId": "admin_group_query_activity_id",
    "AdminGroupQueryCategoryUid": "admin_group_query_category_uid",
    "AdminGroupQueryClassUid": "admin_group_query_class_uid",
    "AdminGroupQueryQueryResultId": "admin_group_query_query_result_id",
    "AdminGroupQuerySeverityId": "admin_group_query_severity_id",
    "AdminGroupQueryStatusId": "admin_group_query_status_id",
    "AdvisoryInstallStateId": "advisory_install_state_id",
    "AffectedPackageTypeId": "affected_package_type_id",
    "AgentTypeId": "agent_type_id",
    "AirborneBroadcastActivityActivityId": "airborne_broadcast_activity_activity_id",
    "AirborneBroadcastActivityCategoryUid": "airborne_broadcast_activity_category_uid",
    "AirborneBroadcastActivityClassUid": "airborne_broadcast_activity_class_uid",
    "AirborneBroadcastActivitySeverityId": "airborne_broadcast_activity_severity_id",
    "AirborneBroadcastActivityStatusId": "airborne_broadcast_activity_status_id",
    "AnalyticTypeId": "analytic_type_id",
    "ApiActivityActivityId": "api_activity_activity_id",
    "ApiActivityCategoryUid": "api_activity_category_uid",
    "ApiActivityClassUid": "api_activity_class_uid",
    "ApiActivitySeverityId": "api_activity_severity_id",
    "ApiActivityStatusId": "api_activity_status_id",
    "ApplicationActivityId": "application_activity_id",
    "ApplicationCategoryUid": "application_category_uid",
    "ApplicationClassUid": "application_class_uid",
    "ApplicationErrorActivityId": "application_error_activity_id",
    "ApplicationErrorCategoryUid": "application_error_category_uid",
    "ApplicationErrorClassUid": "application_error_class_uid",
    "ApplicationErrorSeverityId": "application_error_severity_id",
    "ApplicationErrorStatusId": "application_error_status_id",
    "ApplicationLifecycleActivityId": "application_lifecycle_activity_id",
    "ApplicationLifecycleCategoryUid": "application_lifecycle_category_uid",
    "ApplicationLifecycleClassUid": "application_lifecycle_class_uid",
    "ApplicationLifecycleSeverityId": "application_lifecycle_severity_id",
    "ApplicationLifecycleStatusId": "application_lifecycle_status_id",
    "ApplicationRiskLevelId": "application_risk_level_id",
    "ApplicationSecurityPostureFindingActivityId": "application_security_posture_finding_activity_id",
    "ApplicationSecurityPostureFindingCategoryUid": "application_security_posture_finding_category_uid",
    "ApplicationSecurityPostureFindingClassUid": "application_security_posture_finding_class_uid",
    "ApplicationSecurityPostureFindingConfidenceId": "application_security_posture_finding_confidence_id",
    "ApplicationSecurityPostureFindingSeverityId": "application_security_posture_finding_severity_id",
    "ApplicationSecurityPostureFindingStatusId": "application_security_posture_finding_status_id",
    "ApplicationSeverityId": "application_severity_id",
    "ApplicationStatusId": "application_status_id",
    "AuthFactorFactorTypeId": "auth_factor_factor_type_id",
    "AuthenticationActivityId": "authentication_activity_id",
    "AuthenticationAuthProtocolId": "authentication_auth_protocol_id",
    "AuthenticationCategoryUid": "authentication_category_uid",
    "AuthenticationClassUid": "authentication_class_uid",
    "AuthenticationLogonTypeId": "authentication_logon_type_id",
    "AuthenticationSeverityId": "authentication_severity_id",
    "AuthenticationStatusId": "authentication_status_id",
    "AuthenticationTokenTypeId": "authentication_token_type_id",
    "AuthorizeSessionActivityId": "authorize_session_activity_id",
    "AuthorizeSessionCategoryUid": "authorize_session_category_uid",
    "AuthorizeSessionClassUid": "authorize_session_class_uid",
    "AuthorizeSessionSeverityId": "authorize_session_severity_id",
    "AuthorizeSessionStatusId": "authorize_session_status_id",
    "BaseEventActivityId": "base_event_activity_id",
    "BaseEventCategoryUid": "base_event_category_uid",
    "BaseEventClassUid": "base_event_class_uid",
    "BaseEventSeverityId": "base_event_severity_id",
    "BaseEventStatusId": "base_event_status_id",
    "CheckSeverityId": "check_severity_id",
    "CheckStatusId": "check_status_id",
    "CloudResourcesInventoryInfoActivityId": "cloud_resources_inventory_info_activity_id",
    "CloudResourcesInventoryInfoCategoryUid": "cloud_resources_inventory_info_category_uid",
    "CloudResourcesInventoryInfoClassUid": "cloud_resources_inventory_info_class_uid",
    "CloudResourcesInventoryInfoSeverityId": "cloud_resources_inventory_info_severity_id",
    "CloudResourcesInventoryInfoStatusId": "cloud_resources_inventory_info_status_id",
    "ComplianceFindingActivityId": "compliance_finding_activity_id",
    "ComplianceFindingCategoryUid": "compliance_finding_category_uid",
    "ComplianceFindingClassUid": "compliance_finding_class_uid",
    "ComplianceFindingConfidenceId": "compliance_finding_confidence_id",
    "ComplianceFindingSeverityId": "compliance_finding_severity_id",
    "ComplianceFindingStatusId": "compliance_finding_status_id",
    "ComplianceStatusId": "compliance_status_id",
    "ConfigStateActivityId": "config_state_activity_id",
    "ConfigStateCategoryUid": "config_state_category_uid",
    "ConfigStateClassUid": "config_state_class_uid",
    "ConfigStateSeverityId": "config_state_severity_id",
    "ConfigStateStatusId": "config_state_status_id",
    "CvssDepth": "cvss_depth",
    "DataClassificationCategoryId": "data_classification_category_id",
    "DataClassificationConfidentialityId": "data_classification_confidentiality_id",
    "DataClassificationStatusId": "data_classification_status_id",
    "DataSecurityCategoryId": "data_security_category_id",
    "DataSecurityConfidentialityId": "data_security_confidentiality_id",
    "DataSecurityDataLifecycleStateId": "data_security_data_lifecycle_state_id",
    "DataSecurityDetectionSystemId": "data_security_detection_system_id",
    "DataSecurityFindingActivityId": "data_security_finding_activity_id",
    "DataSecurityFindingCategoryUid": "data_security_finding_category_uid",
    "DataSecurityFindingClassUid": "data_security_finding_class_uid",
    "DataSecurityFindingConfidenceId": "data_security_finding_confidence_id",
    "DataSecurityFindingImpactId": "data_security_finding_impact_id",
    "DataSecurityFindingRiskLevelId": "data_security_finding_risk_level_id",
    "DataSecurityFindingSeverityId": "data_security_finding_severity_id",
    "DataSecurityFindingStatusId": "data_security_finding_status_id",
    "DataSecurityStatusId": "data_security_status_id",
    "DatabaseTypeId": "database_type_id",
    "DatabucketTypeId": "databucket_type_id",
    "DatastoreActivityActivityId": "datastore_activity_activity_id",
    "DatastoreActivityCategoryUid": "datastore_activity_category_uid",
    "DatastoreActivityClassUid": "datastore_activity_class_uid",
    "DatastoreActivitySeverityId": "datastore_activity_severity_id",
    "DatastoreActivityStatusId": "datastore_activity_status_id",
    "DatastoreActivityTypeId": "datastore_activity_type_id",
    "DetectionFindingActivityId": "detection_finding_activity_id",
    "DetectionFindingCategoryUid": "detection_finding_category_uid",
    "DetectionFindingClassUid": "detection_finding_class_uid",
    "DetectionFindingConfidenceId": "detection_finding_confidence_id",
    "DetectionFindingImpactId": "detection_finding_impact_id",
    "DetectionFindingRiskLevelId": "detection_finding_risk_level_id",
    "DetectionFindingSeverityId": "detection_finding_severity_id",
    "DetectionFindingStatusId": "detection_finding_status_id",
    "DeviceConfigStateChangeActivityId": "device_config_state_change_activity_id",
    "DeviceConfigStateChangeCategoryUid": "device_config_state_change_category_uid",
    "DeviceConfigStateChangeClassUid": "device_config_state_change_class_uid",
    "DeviceConfigStateChangePrevSecurityLevelId": "device_config_state_change_prev_security_level_id",
    "DeviceConfigStateChangeSecurityLevelId": "device_config_state_change_security_level_id",
    "DeviceConfigStateChangeSeverityId": "device_config_state_change_severity_id",
    "DeviceConfigStateChangeStateId": "device_config_state_change_state_id",
    "DeviceConfigStateChangeStatusId": "device_config_state_change_status_id",
    "DeviceHwInfoCpuArchitectureId": "device_hw_info_cpu_architecture_id",
    "DeviceRiskLevelId": "device_risk_level_id",
    "DeviceTypeId": "device_type_id",
    "DhcpActivityActivityId": "dhcp_activity_activity_id",
    "DhcpActivityCategoryUid": "dhcp_activity_category_uid",
    "DhcpActivityClassUid": "dhcp_activity_class_uid",
    "DhcpActivitySeverityId": "dhcp_activity_severity_id",
    "DhcpActivityStatusId": "dhcp_activity_status_id",
    "DigitalSignatureAlgorithmId": "digital_signature_algorithm_id",
    "DigitalSignatureStateId": "digital_signature_state_id",
    "DiscoveryActivityId": "discovery_activity_id",
    "DiscoveryCategoryUid": "discovery_category_uid",
    "DiscoveryClassUid": "discovery_class_uid",
    "DiscoveryResultActivityId": "discovery_result_activity_id",
    "DiscoveryResultCategoryUid": "discovery_result_category_uid",
    "DiscoveryResultClassUid": "discovery_result_class_uid",
    "DiscoveryResultQueryResultId": "discovery_result_query_result_id",
    "DiscoveryResultSeverityId": "discovery_result_severity_id",
    "DiscoveryResultStatusId": "discovery_result_status_id",
    "DiscoverySeverityId": "discovery_severity_id",
    "DiscoveryStatusId": "discovery_status_id",
    "DnsActivityActivityId": "dns_activity_activity_id",
    "DnsActivityCategoryUid": "dns_activity_category_uid",
    "DnsActivityClassUid": "dns_activity_class_uid",
    "DnsActivityRcodeId": "dns_activity_rcode_id",
    "DnsActivitySeverityId": "dns_activity_severity_id",
    "DnsActivityStatusId": "dns_activity_status_id",
    "DnsAnswerFlagIds": "dns_answer_flag_ids",
    "DnsQueryOpcodeId": "dns_query_opcode_id",
    "DomainContactTypeId": "domain_contact_type_id",
    "DroneFlightsActivityActivityId": "drone_flights_activity_activity_id",
    "DroneFlightsActivityAuthProtocolId": "drone_flights_activity_auth_protocol_id",
    "DroneFlightsActivityCategoryUid": "drone_flights_activity_category_uid",
    "DroneFlightsActivityClassUid": "drone_flights_activity_class_uid",
    "DroneFlightsActivitySeverityId": "drone_flights_activity_severity_id",
    "DroneFlightsActivityStatusId": "drone_flights_activity_status_id",
    "EmailActivityActivityId": "email_activity_activity_id",
    "EmailActivityCategoryUid": "email_activity_category_uid",
    "EmailActivityClassUid": "email_activity_class_uid",
    "EmailActivityDirectionId": "email_activity_direction_id",
    "EmailActivitySeverityId": "email_activity_severity_id",
    "EmailActivityStatusId": "email_activity_status_id",
    "EmailFileActivityActivityId": "email_file_activity_activity_id",
    "EmailFileActivityCategoryUid": "email_file_activity_category_uid",
    "EmailFileActivityClassUid": "email_file_activity_class_uid",
    "EmailFileActivitySeverityId": "email_file_activity_severity_id",
    "EmailFileActivityStatusId": "email_file_activity_status_id",
    "EmailUrlActivityActivityId": "email_url_activity_activity_id",
    "EmailUrlActivityCategoryUid": "email_url_activity_category_uid",
    "EmailUrlActivityClassUid": "email_url_activity_class_uid",
    "EmailUrlActivitySeverityId": "email_url_activity_severity_id",
    "EmailUrlActivityStatusId": "email_url_activity_status_id",
    "EncryptionDetailsAlgorithmId": "encryption_details_algorithm_id",
    "EndpointTypeId": "endpoint_type_id",
    "EntityManagementActivityId": "entity_management_activity_id",
    "EntityManagementCategoryUid": "entity_management_category_uid",
    "EntityManagementClassUid": "entity_management_class_uid",
    "EntityManagementSeverityId": "entity_management_severity_id",
    "EntityManagementStatusId": "entity_management_status_id",
    "EventLogActvityActivityId": "event_log_actvity_activity_id",
    "EventLogActvityCategoryUid": "event_log_actvity_category_uid",
    "EventLogActvityClassUid": "event_log_actvity_class_uid",
    "EventLogActvityLogTypeId": "event_log_actvity_log_type_id",
    "EventLogActvitySeverityId": "event_log_actvity_severity_id",
    "EventLogActvityStatusId": "event_log_actvity_status_id",
    "EvidenceInfoActivityId": "evidence_info_activity_id",
    "EvidenceInfoCategoryUid": "evidence_info_category_uid",
    "EvidenceInfoClassUid": "evidence_info_class_uid",
    "EvidenceInfoQueryResultId": "evidence_info_query_result_id",
    "EvidenceInfoSeverityId": "evidence_info_severity_id",
    "EvidenceInfoStatusId": "evidence_info_status_id",
    "EvidencesVerdictId": "evidences_verdict_id",
    "FileActivityActivityId": "file_activity_activity_id",
    "FileActivityCategoryUid": "file_activity_category_uid",
    "FileActivityClassUid": "file_activity_class_uid",
    "FileActivitySeverityId": "file_activity_severity_id",
    "FileActivityStatusId": "file_activity_status_id",
    "FileConfidentialityId": "file_confidentiality_id",
    "FileDriveTypeId": "file_drive_type_id",
    "FileHostingActivityId": "file_hosting_activity_id",
    "FileHostingCategoryUid": "file_hosting_category_uid",
    "FileHostingClassUid": "file_hosting_class_uid",
    "FileHostingSeverityId": "file_hosting_severity_id",
    "FileHostingShareTypeId": "file_hosting_share_type_id",
    "FileHostingStatusId": "file_hosting_status_id",
    "FileQueryActivityId": "file_query_activity_id",
    "FileQueryCategoryUid": "file_query_category_uid",
    "FileQueryClassUid": "file_query_class_uid",
    "FileQueryQueryResultId": "file_query_query_result_id",
    "FileQuerySeverityId": "file_query_severity_id",
    "FileQueryStatusId": "file_query_status_id",
    "FileRemediationActivityActivityId": "file_remediation_activity_activity_id",
    "FileRemediationActivityCategoryUid": "file_remediation_activity_category_uid",
    "FileRemediationActivityClassUid": "file_remediation_activity_class_uid",
    "FileRemediationActivitySeverityId": "file_remediation_activity_severity_id",
    "FileRemediationActivityStatusId": "file_remediation_activity_status_id",
    "FileTypeId": "file_type_id",
    "FindingActivityId": "finding_activity_id",
    "FindingCategoryUid": "finding_category_uid",
    "FindingClassUid": "finding_class_uid",
    "FindingConfidenceId": "finding_confidence_id",
    "FindingSeverityId": "finding_severity_id",
    "FindingStatusId": "finding_status_id",
    "FingerprintAlgorithmId": "fingerprint_algorithm_id",
    "FolderQueryActivityId": "folder_query_activity_id",
    "FolderQueryCategoryUid": "folder_query_category_uid",
    "FolderQueryClassUid": "folder_query_class_uid",
    "FolderQueryQueryResultId": "folder_query_query_result_id",
    "FolderQuerySeverityId": "folder_query_severity_id",
    "FolderQueryStatusId": "folder_query_status_id",
    "FtpActivityActivityId": "ftp_activity_activity_id",
    "FtpActivityCategoryUid": "ftp_activity_category_uid",
    "FtpActivityClassUid": "ftp_activity_class_uid",
    "FtpActivitySeverityId": "ftp_activity_severity_id",
    "FtpActivityStatusId": "ftp_activity_status_id",
    "GraphQueryLanguageId": "graph_query_language_id",
    "GroupManagementActivityId": "group_management_activity_id",
    "GroupManagementCategoryUid": "group_management_category_uid",
    "GroupManagementClassUid": "group_management_class_uid",
    "GroupManagementSeverityId": "group_management_severity_id",
    "GroupManagementStatusId": "group_management_status_id",
    "HttpActivityActivityId": "http_activity_activity_id",
    "HttpActivityCategoryUid": "http_activity_category_uid",
    "HttpActivityClassUid": "http_activity_class_uid",
    "HttpActivitySeverityId": "http_activity_severity_id",
    "HttpActivityStatusId": "http_activity_status_id",
    "HttpRequestHttpMethod": "http_request_http_method",
    "IamActivityId": "iam_activity_id",
    "IamCategoryUid": "iam_category_uid",
    "IamClassUid": "iam_class_uid",
    "IamSeverityId": "iam_severity_id",
    "IamStatusId": "iam_status_id",
    "IdpStateId": "idp_state_id",
    "IncidentFindingActivityId": "incident_finding_activity_id",
    "IncidentFindingCategoryUid": "incident_finding_category_uid",
    "IncidentFindingClassUid": "incident_finding_class_uid",
    "IncidentFindingConfidenceId": "incident_finding_confidence_id",
    "IncidentFindingImpactId": "incident_finding_impact_id",
    "IncidentFindingPriorityId": "incident_finding_priority_id",
    "IncidentFindingSeverityId": "incident_finding_severity_id",
    "IncidentFindingStatusId": "incident_finding_status_id",
    "IncidentFindingVerdictId": "incident_finding_verdict_id",
    "InventoryInfoActivityId": "inventory_info_activity_id",
    "InventoryInfoCategoryUid": "inventory_info_category_uid",
    "InventoryInfoClassUid": "inventory_info_class_uid",
    "InventoryInfoSeverityId": "inventory_info_severity_id",
    "InventoryInfoStatusId": "inventory_info_status_id",
    "Ja4FingerprintTypeId": "ja4_fingerprint_type_id",
    "JobQueryActivityId": "job_query_activity_id",
    "JobQueryCategoryUid": "job_query_category_uid",
    "JobQueryClassUid": "job_query_class_uid",
    "JobQueryQueryResultId": "job_query_query_result_id",
    "JobQuerySeverityId": "job_query_severity_id",
    "JobQueryStatusId": "job_query_status_id",
    "JobRunStateId": "job_run_state_id",
    "KbArticleInstallStateId": "kb_article_install_state_id",
    "KernelActivityActivityId": "kernel_activity_activity_id",
    "KernelActivityCategoryUid": "kernel_activity_category_uid",
    "KernelActivityClassUid": "kernel_activity_class_uid",
    "KernelActivitySeverityId": "kernel_activity_severity_id",
    "KernelActivityStatusId": "kernel_activity_status_id",
    "KernelExtensionActivityActivityId": "kernel_extension_activity_activity_id",
    "KernelExtensionActivityCategoryUid": "kernel_extension_activity_category_uid",
    "KernelExtensionActivityClassUid": "kernel_extension_activity_class_uid",
    "KernelExtensionActivitySeverityId": "kernel_extension_activity_severity_id",
    "KernelExtensionActivityStatusId": "kernel_extension_activity_status_id",
    "KernelObjectQueryActivityId": "kernel_object_query_activity_id",
    "KernelObjectQueryCategoryUid": "kernel_object_query_category_uid",
    "KernelObjectQueryClassUid": "kernel_object_query_class_uid",
    "KernelObjectQueryQueryResultId": "kernel_object_query_query_result_id",
    "KernelObjectQuerySeverityId": "kernel_object_query_severity_id",
    "KernelObjectQueryStatusId": "kernel_object_query_status_id",
    "KernelTypeId": "kernel_type_id",
    "KillChainPhasePhaseId": "kill_chain_phase_phase_id",
    "MalwareClassificationIds": "malware_classification_ids",
    "MalwareScanInfoTypeId": "malware_scan_info_type_id",
    "MalwareSeverityId": "malware_severity_id",
    "ManagedEntityTypeId": "managed_entity_type_id",
    "MemoryActivityActivityId": "memory_activity_activity_id",
    "MemoryActivityCategoryUid": "memory_activity_category_uid",
    "MemoryActivityClassUid": "memory_activity_class_uid",
    "MemoryActivitySeverityId": "memory_activity_severity_id",
    "MemoryActivityStatusId": "memory_activity_status_id",
    "ModuleActivityActivityId": "module_activity_activity_id",
    "ModuleActivityCategoryUid": "module_activity_category_uid",
    "ModuleActivityClassUid": "module_activity_class_uid",
    "ModuleActivitySeverityId": "module_activity_severity_id",
    "ModuleActivityStatusId": "module_activity_status_id",
    "ModuleLoadTypeId": "module_load_type_id",
    "ModuleQueryActivityId": "module_query_activity_id",
    "ModuleQueryCategoryUid": "module_query_category_uid",
    "ModuleQueryClassUid": "module_query_class_uid",
    "ModuleQueryQueryResultId": "module_query_query_result_id",
    "ModuleQuerySeverityId": "module_query_severity_id",
    "ModuleQueryStatusId": "module_query_status_id",
    "NetworkActivityActivityId": "network_activity_activity_id",
    "NetworkActivityCategoryUid": "network_activity_category_uid",
    "NetworkActivityClassUid": "network_activity_class_uid",
    "NetworkActivityId": "network_activity_id",
    "NetworkActivitySeverityId": "network_activity_severity_id",
    "NetworkActivityStatusId": "network_activity_status_id",
    "NetworkCategoryUid": "network_category_uid",
    "NetworkClassUid": "network_class_uid",
    "NetworkConnectionInfoBoundaryId": "network_connection_info_boundary_id",
    "NetworkConnectionInfoDirectionId": "network_connection_info_direction_id",
    "NetworkConnectionInfoProtocolVerId": "network_connection_info_protocol_ver_id",
    "NetworkConnectionQueryActivityId": "network_connection_query_activity_id",
    "NetworkConnectionQueryCategoryUid": "network_connection_query_category_uid",
    "NetworkConnectionQueryClassUid": "network_connection_query_class_uid",
    "NetworkConnectionQueryQueryResultId": "network_connection_query_query_result_id",
    "NetworkConnectionQuerySeverityId": "network_connection_query_severity_id",
    "NetworkConnectionQueryStateId": "network_connection_query_state_id",
    "NetworkConnectionQueryStatusId": "network_connection_query_status_id",
    "NetworkEndpointTypeId": "network_endpoint_type_id",
    "NetworkFileActivityActivityId": "network_file_activity_activity_id",
    "NetworkFileActivityCategoryUid": "network_file_activity_category_uid",
    "NetworkFileActivityClassUid": "network_file_activity_class_uid",
    "NetworkFileActivitySeverityId": "network_file_activity_severity_id",
    "NetworkFileActivityStatusId": "network_file_activity_status_id",
    "NetworkInterfaceTypeId": "network_interface_type_id",
    "NetworkProxyTypeId": "network_proxy_type_id",
    "NetworkRemediationActivityActivityId": "network_remediation_activity_activity_id",
    "NetworkRemediationActivityCategoryUid": "network_remediation_activity_category_uid",
    "NetworkRemediationActivityClassUid": "network_remediation_activity_class_uid",
    "NetworkRemediationActivitySeverityId": "network_remediation_activity_severity_id",
    "NetworkRemediationActivityStatusId": "network_remediation_activity_status_id",
    "NetworkSeverityId": "network_severity_id",
    "NetworkStatusId": "network_status_id",
    "NetworksQueryActivityId": "networks_query_activity_id",
    "NetworksQueryCategoryUid": "networks_query_category_uid",
    "NetworksQueryClassUid": "networks_query_class_uid",
    "NetworksQueryQueryResultId": "networks_query_query_result_id",
    "NetworksQuerySeverityId": "networks_query_severity_id",
    "NetworksQueryStatusId": "networks_query_status_id",
    "NtpActivityActivityId": "ntp_activity_activity_id",
    "NtpActivityCategoryUid": "ntp_activity_category_uid",
    "NtpActivityClassUid": "ntp_activity_class_uid",
    "NtpActivitySeverityId": "ntp_activity_severity_id",
    "NtpActivityStatusId": "ntp_activity_status_id",
    "NtpActivityStratumId": "ntp_activity_stratum_id",
    "ObservableTypeId": "observable_type_id",
    "OsTypeId": "os_type_id",
    "OsintConfidenceId": "osint_confidence_id",
    "OsintDetectionPatternTypeId": "osint_detection_pattern_type_id",
    "OsintInventoryInfoActivityId": "osint_inventory_info_activity_id",
    "OsintInventoryInfoCategoryUid": "osint_inventory_info_category_uid",
    "OsintInventoryInfoClassUid": "osint_inventory_info_class_uid",
    "OsintInventoryInfoSeverityId": "osint_inventory_info_severity_id",
    "OsintInventoryInfoStatusId": "osint_inventory_info_status_id",
    "OsintSeverityId": "osint_severity_id",
    "OsintTlp": "osint_tlp",
    "OsintTypeId": "osint_type_id",
    "PackageTypeId": "package_type_id",
    "PatchStateActivityId": "patch_state_activity_id",
    "PatchStateCategoryUid": "patch_state_category_uid",
    "PatchStateClassUid": "patch_state_class_uid",
    "PatchStateSeverityId": "patch_state_severity_id",
    "PatchStateStatusId": "patch_state_status_id",
    "PeripheralDeviceQueryActivityId": "peripheral_device_query_activity_id",
    "PeripheralDeviceQueryCategoryUid": "peripheral_device_query_category_uid",
    "PeripheralDeviceQueryClassUid": "peripheral_device_query_class_uid",
    "PeripheralDeviceQueryQueryResultId": "peripheral_device_query_query_result_id",
    "PeripheralDeviceQuerySeverityId": "peripheral_device_query_severity_id",
    "PeripheralDeviceQueryStatusId": "peripheral_device_query_status_id",
    "ProcessActivityActivityId": "process_activity_activity_id",
    "ProcessActivityCategoryUid": "process_activity_category_uid",
    "ProcessActivityClassUid": "process_activity_class_uid",
    "ProcessActivityInjectionTypeId": "process_activity_injection_type_id",
    "ProcessActivitySeverityId": "process_activity_severity_id",
    "ProcessActivityStatusId": "process_activity_status_id",
    "ProcessIntegrityId": "process_integrity_id",
    "ProcessQueryActivityId": "process_query_activity_id",
    "ProcessQueryCategoryUid": "process_query_category_uid",
    "ProcessQueryClassUid": "process_query_class_uid",
    "ProcessQueryQueryResultId": "process_query_query_result_id",
    "ProcessQuerySeverityId": "process_query_severity_id",
    "ProcessQueryStatusId": "process_query_status_id",
    "ProcessRemediationActivityActivityId": "process_remediation_activity_activity_id",
    "ProcessRemediationActivityCategoryUid": "process_remediation_activity_category_uid",
    "ProcessRemediationActivityClassUid": "process_remediation_activity_class_uid",
    "ProcessRemediationActivitySeverityId": "process_remediation_activity_severity_id",
    "ProcessRemediationActivityStatusId": "process_remediation_activity_status_id",
    "QueryEvidenceQueryTypeId": "query_evidence_query_type_id",
    "QueryEvidenceTcpStateId": "query_evidence_tcp_state_id",
    "RdpActivityActivityId": "rdp_activity_activity_id",
    "RdpActivityCategoryUid": "rdp_activity_category_uid",
    "RdpActivityClassUid": "rdp_activity_class_uid",
    "RdpActivitySeverityId": "rdp_activity_severity_id",
    "RdpActivityStatusId": "rdp_activity_status_id",
    "RelatedEventSeverityId": "related_event_severity_id",
    "RemediationActivityActivityId": "remediation_activity_activity_id",
    "RemediationActivityCategoryUid": "remediation_activity_category_uid",
    "RemediationActivityClassUid": "remediation_activity_class_uid",
    "RemediationActivitySeverityId": "remediation_activity_severity_id",
    "RemediationActivityStatusId": "remediation_activity_status_id",
    "ReputationScoreId": "reputation_score_id",
    "SbomTypeId": "sbom_type_id",
    "ScanActivityActivityId": "scan_activity_activity_id",
    "ScanActivityCategoryUid": "scan_activity_category_uid",
    "ScanActivityClassUid": "scan_activity_class_uid",
    "ScanActivitySeverityId": "scan_activity_severity_id",
    "ScanActivityStatusId": "scan_activity_status_id",
    "ScanTypeId": "scan_type_id",
    "ScheduledJobActivityActivityId": "scheduled_job_activity_activity_id",
    "ScheduledJobActivityCategoryUid": "scheduled_job_activity_category_uid",
    "ScheduledJobActivityClassUid": "scheduled_job_activity_class_uid",
    "ScheduledJobActivitySeverityId": "scheduled_job_activity_severity_id",
    "ScheduledJobActivityStatusId": "scheduled_job_activity_status_id",
    "ScimAuthProtocolId": "scim_auth_protocol_id",
    "ScimStateId": "scim_state_id",
    "ScriptActivityActivityId": "script_activity_activity_id",
    "ScriptActivityCategoryUid": "script_activity_category_uid",
    "ScriptActivityClassUid": "script_activity_class_uid",
    "ScriptActivitySeverityId": "script_activity_severity_id",
    "ScriptActivityStatusId": "script_activity_status_id",
    "ScriptTypeId": "script_type_id",
    "SecurityFindingActivityId": "security_finding_activity_id",
    "SecurityFindingCategoryUid": "security_finding_category_uid",
    "SecurityFindingClassUid": "security_finding_class_uid",
    "SecurityFindingConfidenceId": "security_finding_confidence_id",
    "SecurityFindingImpactId": "security_finding_impact_id",
    "SecurityFindingRiskLevelId": "security_finding_risk_level_id",
    "SecurityFindingSeverityId": "security_finding_severity_id",
    "SecurityFindingStateId": "security_finding_state_id",
    "SecurityFindingStatusId": "security_finding_status_id",
    "SecurityStateStateId": "security_state_state_id",
    "ServiceQueryActivityId": "service_query_activity_id",
    "ServiceQueryCategoryUid": "service_query_category_uid",
    "ServiceQueryClassUid": "service_query_class_uid",
    "ServiceQueryQueryResultId": "service_query_query_result_id",
    "ServiceQuerySeverityId": "service_query_severity_id",
    "ServiceQueryStatusId": "service_query_status_id",
    "SessionQueryActivityId": "session_query_activity_id",
    "SessionQueryCategoryUid": "session_query_category_uid",
    "SessionQueryClassUid": "session_query_class_uid",
    "SessionQueryQueryResultId": "session_query_query_result_id",
    "SessionQuerySeverityId": "session_query_severity_id",
    "SessionQueryStatusId": "session_query_status_id",
    "SmbActivityActivityId": "smb_activity_activity_id",
    "SmbActivityCategoryUid": "smb_activity_category_uid",
    "SmbActivityClassUid": "smb_activity_class_uid",
    "SmbActivitySeverityId": "smb_activity_severity_id",
    "SmbActivityShareTypeId": "smb_activity_share_type_id",
    "SmbActivityStatusId": "smb_activity_status_id",
    "SoftwareComponentRelationshipId": "software_component_relationship_id",
    "SoftwareComponentTypeId": "software_component_type_id",
    "SoftwareInfoActivityId": "software_info_activity_id",
    "SoftwareInfoCategoryUid": "software_info_category_uid",
    "SoftwareInfoClassUid": "software_info_class_uid",
    "SoftwareInfoSeverityId": "software_info_severity_id",
    "SoftwareInfoStatusId": "software_info_status_id",
    "SshActivityActivityId": "ssh_activity_activity_id",
    "SshActivityAuthTypeId": "ssh_activity_auth_type_id",
    "SshActivityCategoryUid": "ssh_activity_category_uid",
    "SshActivityClassUid": "ssh_activity_class_uid",
    "SshActivitySeverityId": "ssh_activity_severity_id",
    "SshActivityStatusId": "ssh_activity_status_id",
    "SsoAuthProtocolId": "sso_auth_protocol_id",
    "StartupItemQueryActivityId": "startup_item_query_activity_id",
    "StartupItemQueryCategoryUid": "startup_item_query_category_uid",
    "StartupItemQueryClassUid": "startup_item_query_class_uid",
    "StartupItemQueryQueryResultId": "startup_item_query_query_result_id",
    "StartupItemQuerySeverityId": "startup_item_query_severity_id",
    "StartupItemQueryStatusId": "startup_item_query_status_id",
    "StartupItemRunModeIds": "startup_item_run_mode_ids",
    "StartupItemRunStateId": "startup_item_run_state_id",
    "StartupItemStartTypeId": "startup_item_start_type_id",
    "StartupItemTypeId": "startup_item_type_id",
    "SystemActivityId": "system_activity_id",
    "SystemCategoryUid": "system_category_uid",
    "SystemClassUid": "system_class_uid",
    "SystemSeverityId": "system_severity_id",
    "SystemStatusId": "system_status_id",
    "ThreatActorTypeId": "threat_actor_type_id",
    "TicketStatusId": "ticket_status_id",
    "TicketTypeId": "ticket_type_id",
    "TimespanTypeId": "timespan_type_id",
    "TlsExtensionTypeId": "tls_extension_type_id",
    "TunnelActivityActivityId": "tunnel_activity_activity_id",
    "TunnelActivityCategoryUid": "tunnel_activity_category_uid",
    "TunnelActivityClassUid": "tunnel_activity_class_uid",
    "TunnelActivitySeverityId": "tunnel_activity_severity_id",
    "TunnelActivityStatusId": "tunnel_activity_status_id",
    "TunnelActivityTunnelTypeId": "tunnel_activity_tunnel_type_id",
    "UnmannedAerialSystemTypeId": "unmanned_aerial_system_type_id",
    "UnmannedSystemOperatingAreaTypeId": "unmanned_system_operating_area_type_id",
    "UnmannedSystemsActivityId": "unmanned_systems_activity_id",
    "UnmannedSystemsCategoryUid": "unmanned_systems_category_uid",
    "UnmannedSystemsClassUid": "unmanned_systems_class_uid",
    "UnmannedSystemsSeverityId": "unmanned_systems_severity_id",
    "UnmannedSystemsStatusId": "unmanned_systems_status_id",
    "UrlCategoryIds": "url_category_ids",
    "UserAccessActivityId": "user_access_activity_id",
    "UserAccessCategoryUid": "user_access_category_uid",
    "UserAccessClassUid": "user_access_class_uid",
    "UserAccessSeverityId": "user_access_severity_id",
    "UserAccessStatusId": "user_access_status_id",
    "UserInventoryActivityId": "user_inventory_activity_id",
    "UserInventoryCategoryUid": "user_inventory_category_uid",
    "UserInventoryClassUid": "user_inventory_class_uid",
    "UserInventorySeverityId": "user_inventory_severity_id",
    "UserInventoryStatusId": "user_inventory_status_id",
    "UserQueryActivityId": "user_query_activity_id",
    "UserQueryCategoryUid": "user_query_category_uid",
    "UserQueryClassUid": "user_query_class_uid",
    "UserQueryQueryResultId": "user_query_query_result_id",
    "UserQuerySeverityId": "user_query_severity_id",
    "UserQueryStatusId": "user_query_status_id",
    "UserRiskLevelId": "user_risk_level_id",
    "UserTypeId": "user_type_id",
    "VendorAttributesSeverityId": "vendor_attributes_severity_id",
    "VulnerabilityFindingActivityId": "vulnerability_finding_activity_id",
    "VulnerabilityFindingCategoryUid": "vulnerability_finding_category_uid",
    "VulnerabilityFindingClassUid": "vulnerability_finding_class_uid",
    "VulnerabilityFindingConfidenceId": "vulnerability_finding_confidence_id",
    "VulnerabilityFindingSeverityId": "vulnerability_finding_severity_id",
    "VulnerabilityFindingStatusId": "vulnerability_finding_status_id",
    "VulnerabilityFixCoverageId": "vulnerability_fix_coverage_id",
    "WebResourceAccessActivityActivityId": "web_resource_access_activity_activity_id",
    "WebResourceAccessActivityCategoryUid": "web_resource_access_activity_category_uid",
    "WebResourceAccessActivityClassUid": "web_resource_access_activity_class_uid",
    "WebResourceAccessActivitySeverityId": "web_resource_access_activity_severity_id",
    "WebResourceAccessActivityStatusId": "web_resource_access_activity_status_id",
    "WebResourcesActivityActivityId": "web_resources_activity_activity_id",
    "WebResourcesActivityCategoryUid": "web_resources_activity_category_uid",
    "WebResourcesActivityClassUid": "web_resources_activity_class_uid",
    "WebResourcesActivitySeverityId": "web_resources_activity_severity_id",
    "WebResourcesActivityStatusId": "web_resources_activity_status_id",
    "WhoisDnssecStatusId": "whois_dnssec_status_id",
}

_imported: set[str] = set()
_rebuild_triggered = False


def __getattr__(name: str) -> Any:
    """Lazily import symbols and trigger model rebuilding if needed."""
    global _rebuild_triggered

    if name not in __all__:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    # Check if already imported and cached
    if name in _imported:
        return globals()[name]

    # Import from individual module file
    module_file = _MODULE_MAP[name]
    module_path = f"{__name__}.{module_file}"
    module = __import__(module_path, fromlist=[name])
    symbol = getattr(module, name)

    # Cache in globals
    globals()[name] = symbol
    _imported.add(name)

    # For models (objects/events), ensure they're rebuilt via version module
    # Only trigger once to avoid recursion
    if False:
        if not _rebuild_triggered:
            _rebuild_triggered = True
            # Trigger version-level batch rebuild
            version_module_name = ".".join(__name__.split(".")[:-1])
            version_module = sys.modules.get(version_module_name)
            if version_module and hasattr(version_module, "_rebuild_all_models"):
                # Call rebuild function directly to avoid recursion through __getattr__
                version_module._rebuild_all_models()

    return symbol


def __dir__() -> list[str]:
    """Support for dir() and autocomplete."""
    return sorted(__all__)
