"""OCSF 1.5.0 objects."""

from __future__ import annotations

import sys
from typing import Any

__all__ = [
    "Account",
    "Actor",
    "Advisory",
    "AffectedCode",
    "AffectedPackage",
    "Agent",
    "Aircraft",
    "AnalysisTarget",
    "Analytic",
    "Anomaly",
    "AnomalyAnalysis",
    "Api",
    "Application",
    "Assessment",
    "Attack",
    "AuthFactor",
    "AuthenticationToken",
    "Authorization",
    "AutonomousSystem",
    "Baseline",
    "Campaign",
    "Certificate",
    "Check",
    "CisBenchmark",
    "CisBenchmarkResult",
    "CisControl",
    "CisCsc",
    "ClassifierDetails",
    "Cloud",
    "Compliance",
    "Container",
    "Cve",
    "Cvss",
    "Cwe",
    "D3fTactic",
    "D3fTechnique",
    "D3fend",
    "DataClassification",
    "DataSecurity",
    "Database",
    "Databucket",
    "DceRpc",
    "Device",
    "DeviceHwInfo",
    "DigitalSignature",
    "DiscoveryDetails",
    "Display",
    "Dns",
    "DnsAnswer",
    "DnsQuery",
    "DomainContact",
    "Edge",
    "Email",
    "EmailAuth",
    "EncryptionDetails",
    "Endpoint",
    "EndpointConnection",
    "Enrichment",
    "Entity",
    "EnvironmentVariable",
    "Epss",
    "Evidences",
    "Extension",
    "Feature",
    "File",
    "Finding",
    "FindingInfo",
    "Fingerprint",
    "FirewallRule",
    "Graph",
    "Group",
    "Hassh",
    "HttpCookie",
    "HttpHeader",
    "HttpRequest",
    "HttpResponse",
    "Idp",
    "Image",
    "Ja4Fingerprint",
    "Job",
    "KbArticle",
    "Kernel",
    "KernelDriver",
    "KeyValueObject",
    "KeyboardInfo",
    "KillChainPhase",
    "LdapPerson",
    "LoadBalancer",
    "Location",
    "Logger",
    "LongString",
    "Malware",
    "MalwareScanInfo",
    "ManagedEntity",
    "Metadata",
    "Metric",
    "Mitigation",
    "Module",
    "NetworkConnectionInfo",
    "NetworkEndpoint",
    "NetworkInterface",
    "NetworkProxy",
    "NetworkTraffic",
    "Node",
    "Object",
    "Observable",
    "Observation",
    "OccurrenceDetails",
    "Organization",
    "Os",
    "Osint",
    "Package",
    "PeripheralDevice",
    "Policy",
    "Process",
    "ProcessEntity",
    "Product",
    "QueryEvidence",
    "QueryInfo",
    "RelatedEvent",
    "Remediation",
    "Reputation",
    "Request",
    "Resource",
    "ResourceDetails",
    "Response",
    "RpcInterface",
    "Rule",
    "San",
    "Sbom",
    "Scan",
    "Scim",
    "Script",
    "SecurityState",
    "Service",
    "Session",
    "SoftwareComponent",
    "Span",
    "Sso",
    "StartupItem",
    "SubTechnique",
    "Table",
    "Tactic",
    "Technique",
    "ThreatActor",
    "Ticket",
    "Timespan",
    "Tls",
    "TlsExtension",
    "Trace",
    "Trait",
    "TransformationInfo",
    "UnmannedAerialSystem",
    "UnmannedSystemOperatingArea",
    "Url",
    "User",
    "VendorAttributes",
    "Vulnerability",
    "WebResource",
    "Whois",
]

# Mapping of class names to their module file names
_MODULE_MAP = {
    "Account": "account",
    "Actor": "actor",
    "Advisory": "advisory",
    "AffectedCode": "affected_code",
    "AffectedPackage": "affected_package",
    "Agent": "agent",
    "Aircraft": "aircraft",
    "AnalysisTarget": "analysis_target",
    "Analytic": "analytic",
    "Anomaly": "anomaly",
    "AnomalyAnalysis": "anomaly_analysis",
    "Api": "api",
    "Application": "application",
    "Assessment": "assessment",
    "Attack": "attack",
    "AuthFactor": "auth_factor",
    "AuthenticationToken": "authentication_token",
    "Authorization": "authorization",
    "AutonomousSystem": "autonomous_system",
    "Baseline": "baseline",
    "Campaign": "campaign",
    "Certificate": "certificate",
    "Check": "check",
    "CisBenchmark": "cis_benchmark",
    "CisBenchmarkResult": "cis_benchmark_result",
    "CisControl": "cis_control",
    "CisCsc": "cis_csc",
    "ClassifierDetails": "classifier_details",
    "Cloud": "cloud",
    "Compliance": "compliance",
    "Container": "container",
    "Cve": "cve",
    "Cvss": "cvss",
    "Cwe": "cwe",
    "D3fTactic": "d3f_tactic",
    "D3fTechnique": "d3f_technique",
    "D3fend": "d3fend",
    "DataClassification": "data_classification",
    "DataSecurity": "data_security",
    "Database": "database",
    "Databucket": "databucket",
    "DceRpc": "dce_rpc",
    "Device": "device",
    "DeviceHwInfo": "device_hw_info",
    "DigitalSignature": "digital_signature",
    "DiscoveryDetails": "discovery_details",
    "Display": "display",
    "Dns": "_dns",
    "DnsAnswer": "dns_answer",
    "DnsQuery": "dns_query",
    "DomainContact": "domain_contact",
    "Edge": "edge",
    "Email": "email",
    "EmailAuth": "email_auth",
    "EncryptionDetails": "encryption_details",
    "Endpoint": "endpoint",
    "EndpointConnection": "endpoint_connection",
    "Enrichment": "enrichment",
    "Entity": "_entity",
    "EnvironmentVariable": "environment_variable",
    "Epss": "epss",
    "Evidences": "evidences",
    "Extension": "extension",
    "Feature": "feature",
    "File": "file",
    "Finding": "finding",
    "FindingInfo": "finding_info",
    "Fingerprint": "fingerprint",
    "FirewallRule": "firewall_rule",
    "Graph": "graph",
    "Group": "group",
    "Hassh": "hassh",
    "HttpCookie": "http_cookie",
    "HttpHeader": "http_header",
    "HttpRequest": "http_request",
    "HttpResponse": "http_response",
    "Idp": "idp",
    "Image": "image",
    "Ja4Fingerprint": "ja4_fingerprint",
    "Job": "job",
    "KbArticle": "kb_article",
    "Kernel": "kernel",
    "KernelDriver": "kernel_driver",
    "KeyValueObject": "key_value_object",
    "KeyboardInfo": "keyboard_info",
    "KillChainPhase": "kill_chain_phase",
    "LdapPerson": "ldap_person",
    "LoadBalancer": "load_balancer",
    "Location": "location",
    "Logger": "logger",
    "LongString": "long_string",
    "Malware": "malware",
    "MalwareScanInfo": "malware_scan_info",
    "ManagedEntity": "managed_entity",
    "Metadata": "metadata",
    "Metric": "metric",
    "Mitigation": "mitigation",
    "Module": "module",
    "NetworkConnectionInfo": "network_connection_info",
    "NetworkEndpoint": "network_endpoint",
    "NetworkInterface": "network_interface",
    "NetworkProxy": "network_proxy",
    "NetworkTraffic": "network_traffic",
    "Node": "node",
    "Object": "object",
    "Observable": "observable",
    "Observation": "observation",
    "OccurrenceDetails": "occurrence_details",
    "Organization": "organization",
    "Os": "os",
    "Osint": "osint",
    "Package": "package",
    "PeripheralDevice": "peripheral_device",
    "Policy": "policy",
    "Process": "process",
    "ProcessEntity": "process_entity",
    "Product": "product",
    "QueryEvidence": "query_evidence",
    "QueryInfo": "query_info",
    "RelatedEvent": "related_event",
    "Remediation": "remediation",
    "Reputation": "reputation",
    "Request": "request",
    "Resource": "_resource",
    "ResourceDetails": "resource_details",
    "Response": "response",
    "RpcInterface": "rpc_interface",
    "Rule": "rule",
    "San": "san",
    "Sbom": "sbom",
    "Scan": "scan",
    "Scim": "scim",
    "Script": "script",
    "SecurityState": "security_state",
    "Service": "service",
    "Session": "session",
    "SoftwareComponent": "software_component",
    "Span": "span",
    "Sso": "sso",
    "StartupItem": "startup_item",
    "SubTechnique": "sub_technique",
    "Table": "table",
    "Tactic": "tactic",
    "Technique": "technique",
    "ThreatActor": "threat_actor",
    "Ticket": "ticket",
    "Timespan": "timespan",
    "Tls": "tls",
    "TlsExtension": "tls_extension",
    "Trace": "trace",
    "Trait": "trait",
    "TransformationInfo": "transformation_info",
    "UnmannedAerialSystem": "unmanned_aerial_system",
    "UnmannedSystemOperatingArea": "unmanned_system_operating_area",
    "Url": "url",
    "User": "user",
    "VendorAttributes": "vendor_attributes",
    "Vulnerability": "vulnerability",
    "WebResource": "web_resource",
    "Whois": "whois",
}

_imported: set[str] = set()
_rebuild_triggered = False


def __getattr__(name: str) -> Any:
    """Lazily import symbols and trigger model rebuilding if needed."""
    global _rebuild_triggered

    if name not in __all__:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    # Check if already imported and cached
    if name in _imported:
        return globals()[name]

    # Import from individual module file
    module_file = _MODULE_MAP[name]
    module_path = f"{__name__}.{module_file}"
    module = __import__(module_path, fromlist=[name])
    symbol = getattr(module, name)

    # Cache in globals
    globals()[name] = symbol
    _imported.add(name)

    # For models (objects/events), ensure they're rebuilt via version module
    # Only trigger once to avoid recursion
    if True:
        if not _rebuild_triggered:
            _rebuild_triggered = True
            # Trigger version-level batch rebuild
            version_module_name = ".".join(__name__.split(".")[:-1])
            version_module = sys.modules.get(version_module_name)
            if version_module and hasattr(version_module, "_rebuild_all_models"):
                # Call rebuild function directly to avoid recursion through __getattr__
                version_module._rebuild_all_models()

    return symbol


def __dir__() -> list[str]:
    """Support for dir() and autocomplete."""
    return sorted(__all__)
