"""OCSF v1.1.0 enumerations."""

from __future__ import annotations

import sys
from typing import Any

__all__ = [
    "AccountChangeActivityId",
    "AccountChangeSeverityId",
    "AccountChangeStatusId",
    "AccountTypeId",
    "AnalyticTypeId",
    "ApiActivityActivityId",
    "ApiActivitySeverityId",
    "ApiActivityStatusId",
    "ApplicationLifecycleActivityId",
    "ApplicationLifecycleSeverityId",
    "ApplicationLifecycleStatusId",
    "ApplicationSeverityId",
    "ApplicationStatusId",
    "AuthenticationActivityId",
    "AuthenticationAuthProtocolId",
    "AuthenticationLogonTypeId",
    "AuthenticationSeverityId",
    "AuthenticationStatusId",
    "AuthorizeSessionActivityId",
    "AuthorizeSessionSeverityId",
    "AuthorizeSessionStatusId",
    "BaseEventSeverityId",
    "BaseEventStatusId",
    "ComplianceFindingActivityId",
    "ComplianceFindingConfidenceId",
    "ComplianceFindingSeverityId",
    "ComplianceFindingStatusId",
    "ComplianceStatusId",
    "ConfigStateActivityId",
    "ConfigStateSeverityId",
    "ConfigStateStatusId",
    "CvssDepth",
    "DatabaseTypeId",
    "DatabucketTypeId",
    "DatastoreActivityActivityId",
    "DatastoreActivitySeverityId",
    "DatastoreActivityStatusId",
    "DatastoreActivityTypeId",
    "DetectionFindingActivityId",
    "DetectionFindingConfidenceId",
    "DetectionFindingImpactId",
    "DetectionFindingRiskLevelId",
    "DetectionFindingSeverityId",
    "DetectionFindingStatusId",
    "DeviceConfigStateChangeActivityId",
    "DeviceConfigStateChangePrevSecurityLevelId",
    "DeviceConfigStateChangeSecurityLevelId",
    "DeviceConfigStateChangeSeverityId",
    "DeviceConfigStateChangeStatusId",
    "DeviceRiskLevelId",
    "DeviceTypeId",
    "DhcpActivityActivityId",
    "DhcpActivitySeverityId",
    "DhcpActivityStatusId",
    "DigitalSignatureAlgorithmId",
    "DiscoveryActivityId",
    "DiscoveryResultActivityId",
    "DiscoveryResultSeverityId",
    "DiscoveryResultStatusId",
    "DiscoverySeverityId",
    "DiscoveryStatusId",
    "DnsActivityActivityId",
    "DnsActivityRcodeId",
    "DnsActivitySeverityId",
    "DnsActivityStatusId",
    "DnsAnswerFlagIds",
    "DnsQueryOpcodeId",
    "EmailActivityActivityId",
    "EmailActivityDirectionId",
    "EmailActivitySeverityId",
    "EmailActivityStatusId",
    "EmailFileActivityActivityId",
    "EmailFileActivitySeverityId",
    "EmailFileActivityStatusId",
    "EmailUrlActivityActivityId",
    "EmailUrlActivitySeverityId",
    "EmailUrlActivityStatusId",
    "EndpointTypeId",
    "EntityManagementActivityId",
    "EntityManagementSeverityId",
    "EntityManagementStatusId",
    "FileActivityActivityId",
    "FileActivitySeverityId",
    "FileActivityStatusId",
    "FileConfidentialityId",
    "FileHostingActivityId",
    "FileHostingSeverityId",
    "FileHostingStatusId",
    "FileTypeId",
    "FindingActivityId",
    "FindingConfidenceId",
    "FindingSeverityId",
    "FindingStatusId",
    "FingerprintAlgorithmId",
    "FtpActivityActivityId",
    "FtpActivitySeverityId",
    "FtpActivityStatusId",
    "GroupManagementActivityId",
    "GroupManagementSeverityId",
    "GroupManagementStatusId",
    "HttpActivityActivityId",
    "HttpActivitySeverityId",
    "HttpActivityStatusId",
    "HttpRequestHttpMethod",
    "IamSeverityId",
    "IamStatusId",
    "IncidentFindingActivityId",
    "IncidentFindingConfidenceId",
    "IncidentFindingImpactId",
    "IncidentFindingPriorityId",
    "IncidentFindingSeverityId",
    "IncidentFindingStatusId",
    "IncidentFindingVerdictId",
    "InventoryInfoActivityId",
    "InventoryInfoSeverityId",
    "InventoryInfoStatusId",
    "JobRunStateId",
    "KernelActivityActivityId",
    "KernelActivitySeverityId",
    "KernelActivityStatusId",
    "KernelExtensionActivityId",
    "KernelExtensionSeverityId",
    "KernelExtensionStatusId",
    "KernelTypeId",
    "KillChainPhasePhaseId",
    "MalwareClassificationIds",
    "MemoryActivityActivityId",
    "MemoryActivitySeverityId",
    "MemoryActivityStatusId",
    "ModuleActivityActivityId",
    "ModuleActivitySeverityId",
    "ModuleActivityStatusId",
    "ModuleLoadTypeId",
    "NetworkActivitySeverityId",
    "NetworkActivityStatusId",
    "NetworkConnectionInfoBoundaryId",
    "NetworkConnectionInfoDirectionId",
    "NetworkConnectionInfoProtocolVerId",
    "NetworkEndpointTypeId",
    "NetworkFileActivityActivityId",
    "NetworkFileActivitySeverityId",
    "NetworkFileActivityStatusId",
    "NetworkInterfaceTypeId",
    "NetworkProxyTypeId",
    "NetworkSeverityId",
    "NetworkStatusId",
    "NtpActivityActivityId",
    "NtpActivitySeverityId",
    "NtpActivityStatusId",
    "NtpActivityStratumId",
    "ObservableTypeId",
    "OsTypeId",
    "PatchStateActivityId",
    "PatchStateSeverityId",
    "PatchStateStatusId",
    "ProcessActivityActivityId",
    "ProcessActivityInjectionTypeId",
    "ProcessActivitySeverityId",
    "ProcessActivityStatusId",
    "ProcessIntegrityId",
    "RdpActivityActivityId",
    "RdpActivitySeverityId",
    "RdpActivityStatusId",
    "ReputationScoreId",
    "ScanActivityActivityId",
    "ScanActivitySeverityId",
    "ScanActivityStatusId",
    "ScanTypeId",
    "ScheduledJobActivityActivityId",
    "ScheduledJobActivitySeverityId",
    "ScheduledJobActivityStatusId",
    "SecurityFindingActivityId",
    "SecurityFindingConfidenceId",
    "SecurityFindingImpactId",
    "SecurityFindingRiskLevelId",
    "SecurityFindingSeverityId",
    "SecurityFindingStateId",
    "SecurityFindingStatusId",
    "SecurityStateStateId",
    "SmbActivityActivityId",
    "SmbActivitySeverityId",
    "SmbActivityShareTypeId",
    "SmbActivityStatusId",
    "SshActivityAuthTypeId",
    "SshActivitySeverityId",
    "SshActivityStatusId",
    "SystemSeverityId",
    "SystemStatusId",
    "TlsExtensionTypeId",
    "UrlCategoryIds",
    "UserAccessActivityId",
    "UserAccessSeverityId",
    "UserAccessStatusId",
    "UserInventoryActivityId",
    "UserInventorySeverityId",
    "UserInventoryStatusId",
    "UserTypeId",
    "VulnerabilityFindingActivityId",
    "VulnerabilityFindingConfidenceId",
    "VulnerabilityFindingSeverityId",
    "VulnerabilityFindingStatusId",
    "WebResourceAccessActivityActivityId",
    "WebResourceAccessActivitySeverityId",
    "WebResourceAccessActivityStatusId",
    "WebResourcesActivityActivityId",
    "WebResourcesActivitySeverityId",
    "WebResourcesActivityStatusId",
]

# Mapping of class names to their module file names
_MODULE_MAP = {
    "AccountChangeActivityId": "account_change_activity_id",
    "AccountChangeSeverityId": "account_change_severity_id",
    "AccountChangeStatusId": "account_change_status_id",
    "AccountTypeId": "account_type_id",
    "AnalyticTypeId": "analytic_type_id",
    "ApiActivityActivityId": "api_activity_activity_id",
    "ApiActivitySeverityId": "api_activity_severity_id",
    "ApiActivityStatusId": "api_activity_status_id",
    "ApplicationLifecycleActivityId": "application_lifecycle_activity_id",
    "ApplicationLifecycleSeverityId": "application_lifecycle_severity_id",
    "ApplicationLifecycleStatusId": "application_lifecycle_status_id",
    "ApplicationSeverityId": "application_severity_id",
    "ApplicationStatusId": "application_status_id",
    "AuthenticationActivityId": "authentication_activity_id",
    "AuthenticationAuthProtocolId": "authentication_auth_protocol_id",
    "AuthenticationLogonTypeId": "authentication_logon_type_id",
    "AuthenticationSeverityId": "authentication_severity_id",
    "AuthenticationStatusId": "authentication_status_id",
    "AuthorizeSessionActivityId": "authorize_session_activity_id",
    "AuthorizeSessionSeverityId": "authorize_session_severity_id",
    "AuthorizeSessionStatusId": "authorize_session_status_id",
    "BaseEventSeverityId": "base_event_severity_id",
    "BaseEventStatusId": "base_event_status_id",
    "ComplianceFindingActivityId": "compliance_finding_activity_id",
    "ComplianceFindingConfidenceId": "compliance_finding_confidence_id",
    "ComplianceFindingSeverityId": "compliance_finding_severity_id",
    "ComplianceFindingStatusId": "compliance_finding_status_id",
    "ComplianceStatusId": "compliance_status_id",
    "ConfigStateActivityId": "config_state_activity_id",
    "ConfigStateSeverityId": "config_state_severity_id",
    "ConfigStateStatusId": "config_state_status_id",
    "CvssDepth": "cvss_depth",
    "DatabaseTypeId": "database_type_id",
    "DatabucketTypeId": "databucket_type_id",
    "DatastoreActivityActivityId": "datastore_activity_activity_id",
    "DatastoreActivitySeverityId": "datastore_activity_severity_id",
    "DatastoreActivityStatusId": "datastore_activity_status_id",
    "DatastoreActivityTypeId": "datastore_activity_type_id",
    "DetectionFindingActivityId": "detection_finding_activity_id",
    "DetectionFindingConfidenceId": "detection_finding_confidence_id",
    "DetectionFindingImpactId": "detection_finding_impact_id",
    "DetectionFindingRiskLevelId": "detection_finding_risk_level_id",
    "DetectionFindingSeverityId": "detection_finding_severity_id",
    "DetectionFindingStatusId": "detection_finding_status_id",
    "DeviceConfigStateChangeActivityId": "device_config_state_change_activity_id",
    "DeviceConfigStateChangePrevSecurityLevelId": "device_config_state_change_prev_security_level_id",
    "DeviceConfigStateChangeSecurityLevelId": "device_config_state_change_security_level_id",
    "DeviceConfigStateChangeSeverityId": "device_config_state_change_severity_id",
    "DeviceConfigStateChangeStatusId": "device_config_state_change_status_id",
    "DeviceRiskLevelId": "device_risk_level_id",
    "DeviceTypeId": "device_type_id",
    "DhcpActivityActivityId": "dhcp_activity_activity_id",
    "DhcpActivitySeverityId": "dhcp_activity_severity_id",
    "DhcpActivityStatusId": "dhcp_activity_status_id",
    "DigitalSignatureAlgorithmId": "digital_signature_algorithm_id",
    "DiscoveryActivityId": "discovery_activity_id",
    "DiscoveryResultActivityId": "discovery_result_activity_id",
    "DiscoveryResultSeverityId": "discovery_result_severity_id",
    "DiscoveryResultStatusId": "discovery_result_status_id",
    "DiscoverySeverityId": "discovery_severity_id",
    "DiscoveryStatusId": "discovery_status_id",
    "DnsActivityActivityId": "dns_activity_activity_id",
    "DnsActivityRcodeId": "dns_activity_rcode_id",
    "DnsActivitySeverityId": "dns_activity_severity_id",
    "DnsActivityStatusId": "dns_activity_status_id",
    "DnsAnswerFlagIds": "dns_answer_flag_ids",
    "DnsQueryOpcodeId": "dns_query_opcode_id",
    "EmailActivityActivityId": "email_activity_activity_id",
    "EmailActivityDirectionId": "email_activity_direction_id",
    "EmailActivitySeverityId": "email_activity_severity_id",
    "EmailActivityStatusId": "email_activity_status_id",
    "EmailFileActivityActivityId": "email_file_activity_activity_id",
    "EmailFileActivitySeverityId": "email_file_activity_severity_id",
    "EmailFileActivityStatusId": "email_file_activity_status_id",
    "EmailUrlActivityActivityId": "email_url_activity_activity_id",
    "EmailUrlActivitySeverityId": "email_url_activity_severity_id",
    "EmailUrlActivityStatusId": "email_url_activity_status_id",
    "EndpointTypeId": "endpoint_type_id",
    "EntityManagementActivityId": "entity_management_activity_id",
    "EntityManagementSeverityId": "entity_management_severity_id",
    "EntityManagementStatusId": "entity_management_status_id",
    "FileActivityActivityId": "file_activity_activity_id",
    "FileActivitySeverityId": "file_activity_severity_id",
    "FileActivityStatusId": "file_activity_status_id",
    "FileConfidentialityId": "file_confidentiality_id",
    "FileHostingActivityId": "file_hosting_activity_id",
    "FileHostingSeverityId": "file_hosting_severity_id",
    "FileHostingStatusId": "file_hosting_status_id",
    "FileTypeId": "file_type_id",
    "FindingActivityId": "finding_activity_id",
    "FindingConfidenceId": "finding_confidence_id",
    "FindingSeverityId": "finding_severity_id",
    "FindingStatusId": "finding_status_id",
    "FingerprintAlgorithmId": "fingerprint_algorithm_id",
    "FtpActivityActivityId": "ftp_activity_activity_id",
    "FtpActivitySeverityId": "ftp_activity_severity_id",
    "FtpActivityStatusId": "ftp_activity_status_id",
    "GroupManagementActivityId": "group_management_activity_id",
    "GroupManagementSeverityId": "group_management_severity_id",
    "GroupManagementStatusId": "group_management_status_id",
    "HttpActivityActivityId": "http_activity_activity_id",
    "HttpActivitySeverityId": "http_activity_severity_id",
    "HttpActivityStatusId": "http_activity_status_id",
    "HttpRequestHttpMethod": "http_request_http_method",
    "IamSeverityId": "iam_severity_id",
    "IamStatusId": "iam_status_id",
    "IncidentFindingActivityId": "incident_finding_activity_id",
    "IncidentFindingConfidenceId": "incident_finding_confidence_id",
    "IncidentFindingImpactId": "incident_finding_impact_id",
    "IncidentFindingPriorityId": "incident_finding_priority_id",
    "IncidentFindingSeverityId": "incident_finding_severity_id",
    "IncidentFindingStatusId": "incident_finding_status_id",
    "IncidentFindingVerdictId": "incident_finding_verdict_id",
    "InventoryInfoActivityId": "inventory_info_activity_id",
    "InventoryInfoSeverityId": "inventory_info_severity_id",
    "InventoryInfoStatusId": "inventory_info_status_id",
    "JobRunStateId": "job_run_state_id",
    "KernelActivityActivityId": "kernel_activity_activity_id",
    "KernelActivitySeverityId": "kernel_activity_severity_id",
    "KernelActivityStatusId": "kernel_activity_status_id",
    "KernelExtensionActivityId": "kernel_extension_activity_id",
    "KernelExtensionSeverityId": "kernel_extension_severity_id",
    "KernelExtensionStatusId": "kernel_extension_status_id",
    "KernelTypeId": "kernel_type_id",
    "KillChainPhasePhaseId": "kill_chain_phase_phase_id",
    "MalwareClassificationIds": "malware_classification_ids",
    "MemoryActivityActivityId": "memory_activity_activity_id",
    "MemoryActivitySeverityId": "memory_activity_severity_id",
    "MemoryActivityStatusId": "memory_activity_status_id",
    "ModuleActivityActivityId": "module_activity_activity_id",
    "ModuleActivitySeverityId": "module_activity_severity_id",
    "ModuleActivityStatusId": "module_activity_status_id",
    "ModuleLoadTypeId": "module_load_type_id",
    "NetworkActivitySeverityId": "network_activity_severity_id",
    "NetworkActivityStatusId": "network_activity_status_id",
    "NetworkConnectionInfoBoundaryId": "network_connection_info_boundary_id",
    "NetworkConnectionInfoDirectionId": "network_connection_info_direction_id",
    "NetworkConnectionInfoProtocolVerId": "network_connection_info_protocol_ver_id",
    "NetworkEndpointTypeId": "network_endpoint_type_id",
    "NetworkFileActivityActivityId": "network_file_activity_activity_id",
    "NetworkFileActivitySeverityId": "network_file_activity_severity_id",
    "NetworkFileActivityStatusId": "network_file_activity_status_id",
    "NetworkInterfaceTypeId": "network_interface_type_id",
    "NetworkProxyTypeId": "network_proxy_type_id",
    "NetworkSeverityId": "network_severity_id",
    "NetworkStatusId": "network_status_id",
    "NtpActivityActivityId": "ntp_activity_activity_id",
    "NtpActivitySeverityId": "ntp_activity_severity_id",
    "NtpActivityStatusId": "ntp_activity_status_id",
    "NtpActivityStratumId": "ntp_activity_stratum_id",
    "ObservableTypeId": "observable_type_id",
    "OsTypeId": "os_type_id",
    "PatchStateActivityId": "patch_state_activity_id",
    "PatchStateSeverityId": "patch_state_severity_id",
    "PatchStateStatusId": "patch_state_status_id",
    "ProcessActivityActivityId": "process_activity_activity_id",
    "ProcessActivityInjectionTypeId": "process_activity_injection_type_id",
    "ProcessActivitySeverityId": "process_activity_severity_id",
    "ProcessActivityStatusId": "process_activity_status_id",
    "ProcessIntegrityId": "process_integrity_id",
    "RdpActivityActivityId": "rdp_activity_activity_id",
    "RdpActivitySeverityId": "rdp_activity_severity_id",
    "RdpActivityStatusId": "rdp_activity_status_id",
    "ReputationScoreId": "reputation_score_id",
    "ScanActivityActivityId": "scan_activity_activity_id",
    "ScanActivitySeverityId": "scan_activity_severity_id",
    "ScanActivityStatusId": "scan_activity_status_id",
    "ScanTypeId": "scan_type_id",
    "ScheduledJobActivityActivityId": "scheduled_job_activity_activity_id",
    "ScheduledJobActivitySeverityId": "scheduled_job_activity_severity_id",
    "ScheduledJobActivityStatusId": "scheduled_job_activity_status_id",
    "SecurityFindingActivityId": "security_finding_activity_id",
    "SecurityFindingConfidenceId": "security_finding_confidence_id",
    "SecurityFindingImpactId": "security_finding_impact_id",
    "SecurityFindingRiskLevelId": "security_finding_risk_level_id",
    "SecurityFindingSeverityId": "security_finding_severity_id",
    "SecurityFindingStateId": "security_finding_state_id",
    "SecurityFindingStatusId": "security_finding_status_id",
    "SecurityStateStateId": "security_state_state_id",
    "SmbActivityActivityId": "smb_activity_activity_id",
    "SmbActivitySeverityId": "smb_activity_severity_id",
    "SmbActivityShareTypeId": "smb_activity_share_type_id",
    "SmbActivityStatusId": "smb_activity_status_id",
    "SshActivityAuthTypeId": "ssh_activity_auth_type_id",
    "SshActivitySeverityId": "ssh_activity_severity_id",
    "SshActivityStatusId": "ssh_activity_status_id",
    "SystemSeverityId": "system_severity_id",
    "SystemStatusId": "system_status_id",
    "TlsExtensionTypeId": "tls_extension_type_id",
    "UrlCategoryIds": "url_category_ids",
    "UserAccessActivityId": "user_access_activity_id",
    "UserAccessSeverityId": "user_access_severity_id",
    "UserAccessStatusId": "user_access_status_id",
    "UserInventoryActivityId": "user_inventory_activity_id",
    "UserInventorySeverityId": "user_inventory_severity_id",
    "UserInventoryStatusId": "user_inventory_status_id",
    "UserTypeId": "user_type_id",
    "VulnerabilityFindingActivityId": "vulnerability_finding_activity_id",
    "VulnerabilityFindingConfidenceId": "vulnerability_finding_confidence_id",
    "VulnerabilityFindingSeverityId": "vulnerability_finding_severity_id",
    "VulnerabilityFindingStatusId": "vulnerability_finding_status_id",
    "WebResourceAccessActivityActivityId": "web_resource_access_activity_activity_id",
    "WebResourceAccessActivitySeverityId": "web_resource_access_activity_severity_id",
    "WebResourceAccessActivityStatusId": "web_resource_access_activity_status_id",
    "WebResourcesActivityActivityId": "web_resources_activity_activity_id",
    "WebResourcesActivitySeverityId": "web_resources_activity_severity_id",
    "WebResourcesActivityStatusId": "web_resources_activity_status_id",
}

_imported: set[str] = set()
_rebuild_triggered = False


def __getattr__(name: str) -> Any:
    """Lazily import symbols and trigger model rebuilding if needed."""
    global _rebuild_triggered

    if name not in __all__:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    # Check if already imported and cached
    if name in _imported:
        return globals()[name]

    # Import from individual module file
    module_file = _MODULE_MAP[name]
    module_path = f"{__name__}.{module_file}"
    module = __import__(module_path, fromlist=[name])
    symbol = getattr(module, name)

    # Cache in globals
    globals()[name] = symbol
    _imported.add(name)

    # For models (objects/events), ensure they're rebuilt via version module
    # Only trigger once to avoid recursion
    if False:
        if not _rebuild_triggered:
            _rebuild_triggered = True
            # Trigger version-level batch rebuild
            version_module_name = ".".join(__name__.split(".")[:-1])
            version_module = sys.modules.get(version_module_name)
            if version_module and hasattr(version_module, "_rebuild_all_models"):
                # Call rebuild function directly to avoid recursion through __getattr__
                version_module._rebuild_all_models()

    return symbol


def __dir__() -> list[str]:
    """Support for dir() and autocomplete."""
    return sorted(__all__)
