"""Detection Finding event class."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from pydantic import Field, model_validator

from ocsf._base import OCSFBaseModel
from ocsf._sibling_enum import SiblingEnum

if TYPE_CHECKING:
    from ocsf.v1_1_0.objects.device import Device
    from ocsf.v1_1_0.objects.enrichment import Enrichment
    from ocsf.v1_1_0.objects.evidences import Evidences
    from ocsf.v1_1_0.objects.finding_info import FindingInfo
    from ocsf.v1_1_0.objects.metadata import Metadata
    from ocsf.v1_1_0.objects.object import Object
    from ocsf.v1_1_0.objects.observable import Observable
    from ocsf.v1_1_0.objects.remediation import Remediation
    from ocsf.v1_1_0.objects.resource_details import ResourceDetails
    from ocsf.v1_1_0.objects.vulnerability import Vulnerability


class DetectionFinding(OCSFBaseModel):
    """A Detection Finding describes detections or alerts generated by security products using correlation engines, detection engines or other methodologies. Note: if the product is a security control, the <code>security_control</code> profile should be applied and its <code>attacks</code> information should be duplicated into the <code>finding_info</code> object.

    OCSF Class UID: 4
    Category: findings

    See: https://schema.ocsf.io/1.1.0/classes/detection_finding
    """

    # Nested Enums for sibling attribute pairs
    class SeverityId(SiblingEnum):
        """<p>The normalized identifier of the event/finding severity.</p>The normalized severity is a measurement the effort and expense required to manage and resolve an event or incident. Smaller numerical values represent lower impact events, and larger numerical values represent higher impact events.

        OCSF Attribute: severity_id
        """

        UNKNOWN = 0
        INFORMATIONAL = 1
        LOW = 2
        MEDIUM = 3
        HIGH = 4
        CRITICAL = 5
        FATAL = 6
        OTHER = 99

        @classmethod
        def _get_label_map(cls) -> dict[int, str]:
            return {
                0: "Unknown",
                1: "Informational",
                2: "Low",
                3: "Medium",
                4: "High",
                5: "Critical",
                6: "Fatal",
                99: "Other",
            }

    class StatusId(SiblingEnum):
        """The normalized status identifier of the Finding, set by the consumer.

        OCSF Attribute: status_id
        """

        NEW = 1
        IN_PROGRESS = 2
        SUPPRESSED = 3
        RESOLVED = 4

        @classmethod
        def _get_label_map(cls) -> dict[int, str]:
            return {
                1: "New",
                2: "In Progress",
                3: "Suppressed",
                4: "Resolved",
            }

    class ActivityId(SiblingEnum):
        """The normalized identifier of the finding activity.

        OCSF Attribute: activity_id
        """

        CREATE = 1
        UPDATE = 2
        CLOSE = 3

        @classmethod
        def _get_label_map(cls) -> dict[int, str]:
            return {
                1: "Create",
                2: "Update",
                3: "Close",
            }

    class ConfidenceId(SiblingEnum):
        """The normalized confidence refers to the accuracy of the rule that created the finding. A rule with a low confidence means that the finding scope is wide and may create finding reports that may not be malicious in nature.

        OCSF Attribute: confidence_id
        """

        UNKNOWN = 0
        LOW = 1
        MEDIUM = 2
        HIGH = 3
        OTHER = 99

        @classmethod
        def _get_label_map(cls) -> dict[int, str]:
            return {
                0: "Unknown",
                1: "Low",
                2: "Medium",
                3: "High",
                99: "Other",
            }

    class ImpactId(SiblingEnum):
        """The normalized impact of the finding.

        OCSF Attribute: impact_id
        """

        UNKNOWN = 0
        LOW = 1
        MEDIUM = 2
        HIGH = 3
        CRITICAL = 4
        OTHER = 99

        @classmethod
        def _get_label_map(cls) -> dict[int, str]:
            return {
                0: "Unknown",
                1: "Low",
                2: "Medium",
                3: "High",
                4: "Critical",
                99: "Other",
            }

    class RiskLevelId(SiblingEnum):
        """The normalized risk level id.

        OCSF Attribute: risk_level_id
        """

        INFO = 0
        LOW = 1
        MEDIUM = 2
        HIGH = 3
        CRITICAL = 4

        @classmethod
        def _get_label_map(cls) -> dict[int, str]:
            return {
                0: "Info",
                1: "Low",
                2: "Medium",
                3: "High",
                4: "Critical",
            }

    # Class identifiers
    class_uid: Literal[4] = Field(
        default=4, description="The unique identifier of the event class."
    )
    category_uid: Literal[0] = Field(default=0, description="The category unique identifier.")
    finding_info: FindingInfo = Field(
        ..., description="Describes the supporting information about a generated finding."
    )
    metadata: Metadata = Field(
        ..., description="The metadata associated with the event or a finding."
    )
    severity_id: SeverityId = Field(
        ...,
        description="<p>The normalized identifier of the event/finding severity.</p>The normalized severity is a measurement the effort and expense required to manage and resolve an event or incident. Smaller numerical values represent lower impact events, and larger numerical values represent higher impact events.",
    )
    activity_id: ActivityId | None = Field(
        default=None, description="The normalized identifier of the finding activity."
    )
    activity_name: str | None = Field(
        default=None,
        description="The finding activity name, as defined by the <code>activity_id</code>.",
    )
    comment: str | None = Field(
        default=None, description="A user provided comment about the finding."
    )
    confidence: str | None = Field(
        default=None,
        description="The confidence, normalized to the caption of the confidence_id value. In the case of 'Other', it is defined by the event source.",
    )
    confidence_id: ConfidenceId | None = Field(
        default=None,
        description="The normalized confidence refers to the accuracy of the rule that created the finding. A rule with a low confidence means that the finding scope is wide and may create finding reports that may not be malicious in nature. [Recommended]",
    )
    confidence_score: int | None = Field(
        default=None, description="The confidence score as reported by the event source."
    )
    device: Device | None = Field(
        default=None,
        description="Describes the affected device/host. It can be used in conjunction with <code>Affected Resource(s)</code>. <p> e.g. Specific details about an AWS EC2 instance, that is affected by the Finding.</p>",
    )
    end_time: int | None = Field(
        default=None, description="The time of the most recent event included in the finding."
    )
    enrichments: list[Enrichment] | None = Field(
        default=None,
        description='The additional information from an external data source, which is associated with the event or a finding. For example add location information for the IP address in the DNS answers:</p><code>[{"name": "answers.ip", "value": "92.24.47.250", "type": "location", "data": {"city": "Socotra", "continent": "Asia", "coordinates": [-25.4153, 17.0743], "country": "YE", "desc": "Yemen"}}]</code>',
    )
    evidences: list[Evidences] | None = Field(
        default=None,
        description="Describes various evidence artifacts associated to the activity/activities that triggered a security detection. [Recommended]",
    )
    impact: str | None = Field(
        default=None,
        description="The impact , normalized to the caption of the impact_id value. In the case of 'Other', it is defined by the event source.",
    )
    impact_id: ImpactId | None = Field(
        default=None, description="The normalized impact of the finding."
    )
    impact_score: int | None = Field(
        default=None, description="The impact of the finding, valid range 0-100."
    )
    include: str | None = Field(default=None, description="")
    message: str | None = Field(
        default=None,
        description="The description of the event/finding, as defined by the source. [Recommended]",
    )
    observables: list[Observable] | None = Field(
        default=None, description="The observables associated with the event or a finding."
    )
    raw_data: str | None = Field(
        default=None, description="The raw event/finding data as received from the source."
    )
    remediation: Remediation | None = Field(
        default=None,
        description="Describes the recommended remediation steps to address identified issue(s).",
    )
    resources: list[ResourceDetails] | None = Field(
        default=None,
        description="Describes details about resources that were the target of the activity that triggered the finding. [Recommended]",
    )
    risk_level: str | None = Field(
        default=None,
        description="The risk level, normalized to the caption of the risk_level_id value. In the case of 'Other', it is defined by the event source.",
    )
    risk_level_id: RiskLevelId | None = Field(
        default=None, description="The normalized risk level id."
    )
    risk_score: int | None = Field(
        default=None, description="The risk score as reported by the event source."
    )
    severity: str | None = Field(
        default=None,
        description="The event/finding severity, normalized to the caption of the severity_id value. In the case of 'Other', it is defined by the source.",
    )
    start_time: int | None = Field(
        default=None, description="The time of the least recent event included in the finding."
    )
    status: str | None = Field(
        default=None,
        description="The normalized status of the Finding set by the consumer normalized to the caption of the status_id value. In the case of 'Other', it is defined by the source.",
    )
    status_code: str | None = Field(
        default=None,
        description="The event status code, as reported by the event source.<br /><br />For example, in a Windows Failed Authentication event, this would be the value of 'Failure Code', e.g. 0x18.",
    )
    status_detail: str | None = Field(
        default=None,
        description="The status details contains additional information about the event/finding outcome.",
    )
    status_id: StatusId | None = Field(
        default=None,
        description="The normalized status identifier of the Finding, set by the consumer. [Recommended]",
    )
    unmapped: Object | None = Field(
        default=None,
        description="The attributes that are not mapped to the event schema. The names and values of those attributes are specific to the event source.",
    )
    vulnerabilities: list[Vulnerability] | None = Field(
        default=None, description="Describes vulnerabilities reported in a Detection Finding."
    )

    @model_validator(mode="before")
    @classmethod
    def _reconcile_siblings(cls, data: Any) -> Any:
        """Reconcile sibling attribute pairs during parsing.

        For each sibling pair (e.g., activity_id/activity_name):
        - If both present: validate they match, use canonical label casing
        - If only ID: extrapolate label from enum
        - If only label: extrapolate ID from enum (unknown → OTHER=99)
        - If neither: leave for field validation to handle required/optional

        Special handling for type_uid:
        - Auto-calculated as class_uid * 100 + activity_id if not provided
        - Validated against activity_id if both provided
        """
        if not isinstance(data, dict):
            return data

        # Sibling pairs for this event class
        siblings: list[tuple[str, str, type[SiblingEnum]]] = [
            ("severity_id", "severity", cls.SeverityId),
            ("status_id", "status", cls.StatusId),
            ("activity_id", "activity_name", cls.ActivityId),
            ("confidence_id", "confidence", cls.ConfidenceId),
            ("impact_id", "impact", cls.ImpactId),
            ("risk_level_id", "risk_level", cls.RiskLevelId),
        ]

        for id_field, label_field, enum_cls in siblings:
            id_val = data.get(id_field)
            label_val = data.get(label_field)

            has_id = id_val is not None
            has_label = label_val is not None

            if has_id and has_label:
                # Both present: validate consistency
                try:
                    enum_member = enum_cls(id_val)
                except (ValueError, KeyError) as e:
                    raise ValueError(f"Invalid {id_field} value: {id_val}") from e

                expected_label = enum_member.label

                # OTHER (99) allows any custom label
                if enum_member.value != 99:
                    if expected_label.lower() != str(label_val).lower():
                        raise ValueError(
                            f"{id_field}={id_val} ({expected_label}) "
                            f"does not match {label_field}={label_val!r}"
                        )
                    # Use canonical label casing
                    data[label_field] = expected_label
                # For OTHER, preserve the custom label as-is

            elif has_id:
                # Only ID provided: extrapolate label
                try:
                    enum_member = enum_cls(id_val)
                    data[label_field] = enum_member.label
                except (ValueError, KeyError) as e:
                    raise ValueError(f"Invalid {id_field} value: {id_val}") from e

            elif has_label:
                # Only label provided: extrapolate ID
                try:
                    enum_member = enum_cls(str(label_val))
                    data[id_field] = enum_member.value
                    data[label_field] = enum_member.label  # Canonical casing
                except (ValueError, KeyError):
                    # Unknown label during JSON parsing → map to OTHER (99) if available
                    # This is lenient for untrusted data, unlike direct enum construction
                    if hasattr(enum_cls, "OTHER"):
                        data[id_field] = 99
                        data[label_field] = "Other"  # Use canonical OTHER label
                    else:
                        raise ValueError(
                            f"Unknown {label_field} value: {label_val!r} "
                            f"and {enum_cls.__name__} has no OTHER member"
                        ) from None

        return data
