"""OCSF v1.1.0 Pydantic models."""

# Lazy imports for performance - modules are loaded on first access
from __future__ import annotations

import sys
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    # Type checking needs to see all exports
    from ocsf.v1_1_0.enums import (
        AccountChangeActivityId,
        AccountChangeSeverityId,
        AccountChangeStatusId,
        AccountTypeId,
        AnalyticTypeId,
        ApiActivityActivityId,
        ApiActivitySeverityId,
        ApiActivityStatusId,
        ApplicationLifecycleActivityId,
        ApplicationLifecycleSeverityId,
        ApplicationLifecycleStatusId,
        ApplicationSeverityId,
        ApplicationStatusId,
        AuthenticationActivityId,
        AuthenticationAuthProtocolId,
        AuthenticationLogonTypeId,
        AuthenticationSeverityId,
        AuthenticationStatusId,
        AuthorizeSessionActivityId,
        AuthorizeSessionSeverityId,
        AuthorizeSessionStatusId,
        BaseEventSeverityId,
        BaseEventStatusId,
        ComplianceFindingActivityId,
        ComplianceFindingConfidenceId,
        ComplianceFindingSeverityId,
        ComplianceFindingStatusId,
        ComplianceStatusId,
        ConfigStateActivityId,
        ConfigStateSeverityId,
        ConfigStateStatusId,
        CvssDepth,
        DatabaseTypeId,
        DatabucketTypeId,
        DatastoreActivityActivityId,
        DatastoreActivitySeverityId,
        DatastoreActivityStatusId,
        DatastoreActivityTypeId,
        DetectionFindingActivityId,
        DetectionFindingConfidenceId,
        DetectionFindingImpactId,
        DetectionFindingRiskLevelId,
        DetectionFindingSeverityId,
        DetectionFindingStatusId,
        DeviceConfigStateChangeActivityId,
        DeviceConfigStateChangePrevSecurityLevelId,
        DeviceConfigStateChangeSecurityLevelId,
        DeviceConfigStateChangeSeverityId,
        DeviceConfigStateChangeStatusId,
        DeviceRiskLevelId,
        DeviceTypeId,
        DhcpActivityActivityId,
        DhcpActivitySeverityId,
        DhcpActivityStatusId,
        DigitalSignatureAlgorithmId,
        DiscoveryActivityId,
        DiscoveryResultActivityId,
        DiscoveryResultSeverityId,
        DiscoveryResultStatusId,
        DiscoverySeverityId,
        DiscoveryStatusId,
        DnsActivityActivityId,
        DnsActivityRcodeId,
        DnsActivitySeverityId,
        DnsActivityStatusId,
        DnsAnswerFlagIds,
        DnsQueryOpcodeId,
        EmailActivityActivityId,
        EmailActivityDirectionId,
        EmailActivitySeverityId,
        EmailActivityStatusId,
        EmailFileActivityActivityId,
        EmailFileActivitySeverityId,
        EmailFileActivityStatusId,
        EmailUrlActivityActivityId,
        EmailUrlActivitySeverityId,
        EmailUrlActivityStatusId,
        EndpointTypeId,
        EntityManagementActivityId,
        EntityManagementSeverityId,
        EntityManagementStatusId,
        FileActivityActivityId,
        FileActivitySeverityId,
        FileActivityStatusId,
        FileConfidentialityId,
        FileHostingActivityId,
        FileHostingSeverityId,
        FileHostingStatusId,
        FileTypeId,
        FindingActivityId,
        FindingConfidenceId,
        FindingSeverityId,
        FindingStatusId,
        FingerprintAlgorithmId,
        FtpActivityActivityId,
        FtpActivitySeverityId,
        FtpActivityStatusId,
        GroupManagementActivityId,
        GroupManagementSeverityId,
        GroupManagementStatusId,
        HttpActivityActivityId,
        HttpActivitySeverityId,
        HttpActivityStatusId,
        HttpRequestHttpMethod,
        IamSeverityId,
        IamStatusId,
        IncidentFindingActivityId,
        IncidentFindingConfidenceId,
        IncidentFindingImpactId,
        IncidentFindingPriorityId,
        IncidentFindingSeverityId,
        IncidentFindingStatusId,
        IncidentFindingVerdictId,
        InventoryInfoActivityId,
        InventoryInfoSeverityId,
        InventoryInfoStatusId,
        JobRunStateId,
        KernelActivityActivityId,
        KernelActivitySeverityId,
        KernelActivityStatusId,
        KernelExtensionActivityId,
        KernelExtensionSeverityId,
        KernelExtensionStatusId,
        KernelTypeId,
        KillChainPhasePhaseId,
        MalwareClassificationIds,
        MemoryActivityActivityId,
        MemoryActivitySeverityId,
        MemoryActivityStatusId,
        ModuleActivityActivityId,
        ModuleActivitySeverityId,
        ModuleActivityStatusId,
        ModuleLoadTypeId,
        NetworkActivitySeverityId,
        NetworkActivityStatusId,
        NetworkConnectionInfoBoundaryId,
        NetworkConnectionInfoDirectionId,
        NetworkConnectionInfoProtocolVerId,
        NetworkEndpointTypeId,
        NetworkFileActivityActivityId,
        NetworkFileActivitySeverityId,
        NetworkFileActivityStatusId,
        NetworkInterfaceTypeId,
        NetworkProxyTypeId,
        NetworkSeverityId,
        NetworkStatusId,
        NtpActivityActivityId,
        NtpActivitySeverityId,
        NtpActivityStatusId,
        NtpActivityStratumId,
        ObservableTypeId,
        OsTypeId,
        PatchStateActivityId,
        PatchStateSeverityId,
        PatchStateStatusId,
        ProcessActivityActivityId,
        ProcessActivityInjectionTypeId,
        ProcessActivitySeverityId,
        ProcessActivityStatusId,
        ProcessIntegrityId,
        RdpActivityActivityId,
        RdpActivitySeverityId,
        RdpActivityStatusId,
        ReputationScoreId,
        ScanActivityActivityId,
        ScanActivitySeverityId,
        ScanActivityStatusId,
        ScanTypeId,
        ScheduledJobActivityActivityId,
        ScheduledJobActivitySeverityId,
        ScheduledJobActivityStatusId,
        SecurityFindingActivityId,
        SecurityFindingConfidenceId,
        SecurityFindingImpactId,
        SecurityFindingRiskLevelId,
        SecurityFindingSeverityId,
        SecurityFindingStateId,
        SecurityFindingStatusId,
        SecurityStateStateId,
        SmbActivityActivityId,
        SmbActivitySeverityId,
        SmbActivityShareTypeId,
        SmbActivityStatusId,
        SshActivityAuthTypeId,
        SshActivitySeverityId,
        SshActivityStatusId,
        SystemSeverityId,
        SystemStatusId,
        TlsExtensionTypeId,
        UrlCategoryIds,
        UserAccessActivityId,
        UserAccessSeverityId,
        UserAccessStatusId,
        UserInventoryActivityId,
        UserInventorySeverityId,
        UserInventoryStatusId,
        UserTypeId,
        VulnerabilityFindingActivityId,
        VulnerabilityFindingConfidenceId,
        VulnerabilityFindingSeverityId,
        VulnerabilityFindingStatusId,
        WebResourceAccessActivityActivityId,
        WebResourceAccessActivitySeverityId,
        WebResourceAccessActivityStatusId,
        WebResourcesActivityActivityId,
        WebResourcesActivitySeverityId,
        WebResourcesActivityStatusId,
    )
    from ocsf.v1_1_0.events import (
        AccountChange,
        ApiActivity,
        ApplicationLifecycle,
        Authentication,
        AuthorizeSession,
        ComplianceFinding,
        ConfigState,
        DatastoreActivity,
        DetectionFinding,
        DeviceConfigStateChange,
        DhcpActivity,
        DnsActivity,
        EmailActivity,
        EmailFileActivity,
        EmailUrlActivity,
        EntityManagement,
        FileActivity,
        FileHosting,
        FtpActivity,
        GroupManagement,
        HttpActivity,
        IncidentFinding,
        InventoryInfo,
        KernelActivity,
        KernelExtension,
        MemoryActivity,
        ModuleActivity,
        NetworkActivity,
        NetworkFileActivity,
        NtpActivity,
        PatchState,
        ProcessActivity,
        RdpActivity,
        ScanActivity,
        ScheduledJobActivity,
        SecurityFinding,
        SmbActivity,
        SshActivity,
        UserAccess,
        UserInventory,
        VulnerabilityFinding,
        WebResourceAccessActivity,
        WebResourcesActivity,
    )
    from ocsf.v1_1_0.objects import (
        Account,
        Actor,
        AffectedCode,
        AffectedPackage,
        Analytic,
        Api,
        Attack,
        Authorization,
        Certificate,
        CisBenchmark,
        CisBenchmarkResult,
        CisControl,
        CisCsc,
        Cloud,
        Compliance,
        Container,
        Cve,
        Cvss,
        Cwe,
        Database,
        Databucket,
        DceRpc,
        Device,
        DeviceHwInfo,
        DigitalSignature,
        Display,
        Dns,
        DnsAnswer,
        DnsQuery,
        Email,
        EmailAuth,
        Endpoint,
        EndpointConnection,
        Enrichment,
        Entity,
        Epss,
        Evidences,
        Extension,
        Feature,
        File,
        Finding,
        FindingInfo,
        Fingerprint,
        FirewallRule,
        Group,
        Hassh,
        HttpCookie,
        HttpHeader,
        HttpRequest,
        HttpResponse,
        Idp,
        Image,
        Job,
        KbArticle,
        Kernel,
        KernelDriver,
        KeyboardInfo,
        KillChainPhase,
        LdapPerson,
        LoadBalancer,
        Location,
        Logger,
        Malware,
        ManagedEntity,
        Metadata,
        Metric,
        Module,
        NetworkConnectionInfo,
        NetworkEndpoint,
        NetworkInterface,
        NetworkProxy,
        NetworkTraffic,
        Object,
        Observable,
        Organization,
        Os,
        Package,
        PeripheralDevice,
        Policy,
        Process,
        Product,
        QueryInfo,
        RelatedEvent,
        Remediation,
        Reputation,
        Request,
        Resource,
        ResourceDetails,
        Response,
        RpcInterface,
        Rule,
        San,
        Scan,
        SecurityState,
        Service,
        Session,
        SubTechnique,
        Table,
        Tactic,
        Technique,
        Tls,
        TlsExtension,
        Url,
        User,
        Vulnerability,
        WebResource,
    )

__all__ = [
    "Account",
    "AccountChange",
    "AccountChangeActivityId",
    "AccountChangeSeverityId",
    "AccountChangeStatusId",
    "AccountTypeId",
    "Actor",
    "AffectedCode",
    "AffectedPackage",
    "Analytic",
    "AnalyticTypeId",
    "Api",
    "ApiActivity",
    "ApiActivityActivityId",
    "ApiActivitySeverityId",
    "ApiActivityStatusId",
    "ApplicationLifecycle",
    "ApplicationLifecycleActivityId",
    "ApplicationLifecycleSeverityId",
    "ApplicationLifecycleStatusId",
    "ApplicationSeverityId",
    "ApplicationStatusId",
    "Attack",
    "Authentication",
    "AuthenticationActivityId",
    "AuthenticationAuthProtocolId",
    "AuthenticationLogonTypeId",
    "AuthenticationSeverityId",
    "AuthenticationStatusId",
    "Authorization",
    "AuthorizeSession",
    "AuthorizeSessionActivityId",
    "AuthorizeSessionSeverityId",
    "AuthorizeSessionStatusId",
    "BaseEventSeverityId",
    "BaseEventStatusId",
    "Certificate",
    "CisBenchmark",
    "CisBenchmarkResult",
    "CisControl",
    "CisCsc",
    "Cloud",
    "Compliance",
    "ComplianceFinding",
    "ComplianceFindingActivityId",
    "ComplianceFindingConfidenceId",
    "ComplianceFindingSeverityId",
    "ComplianceFindingStatusId",
    "ComplianceStatusId",
    "ConfigState",
    "ConfigStateActivityId",
    "ConfigStateSeverityId",
    "ConfigStateStatusId",
    "Container",
    "Cve",
    "Cvss",
    "CvssDepth",
    "Cwe",
    "Database",
    "DatabaseTypeId",
    "Databucket",
    "DatabucketTypeId",
    "DatastoreActivity",
    "DatastoreActivityActivityId",
    "DatastoreActivitySeverityId",
    "DatastoreActivityStatusId",
    "DatastoreActivityTypeId",
    "DceRpc",
    "DetectionFinding",
    "DetectionFindingActivityId",
    "DetectionFindingConfidenceId",
    "DetectionFindingImpactId",
    "DetectionFindingRiskLevelId",
    "DetectionFindingSeverityId",
    "DetectionFindingStatusId",
    "Device",
    "DeviceConfigStateChange",
    "DeviceConfigStateChangeActivityId",
    "DeviceConfigStateChangePrevSecurityLevelId",
    "DeviceConfigStateChangeSecurityLevelId",
    "DeviceConfigStateChangeSeverityId",
    "DeviceConfigStateChangeStatusId",
    "DeviceHwInfo",
    "DeviceRiskLevelId",
    "DeviceTypeId",
    "DhcpActivity",
    "DhcpActivityActivityId",
    "DhcpActivitySeverityId",
    "DhcpActivityStatusId",
    "DigitalSignature",
    "DigitalSignatureAlgorithmId",
    "DiscoveryActivityId",
    "DiscoveryResultActivityId",
    "DiscoveryResultSeverityId",
    "DiscoveryResultStatusId",
    "DiscoverySeverityId",
    "DiscoveryStatusId",
    "Display",
    "Dns",
    "DnsActivity",
    "DnsActivityActivityId",
    "DnsActivityRcodeId",
    "DnsActivitySeverityId",
    "DnsActivityStatusId",
    "DnsAnswer",
    "DnsAnswerFlagIds",
    "DnsQuery",
    "DnsQueryOpcodeId",
    "Email",
    "EmailActivity",
    "EmailActivityActivityId",
    "EmailActivityDirectionId",
    "EmailActivitySeverityId",
    "EmailActivityStatusId",
    "EmailAuth",
    "EmailFileActivity",
    "EmailFileActivityActivityId",
    "EmailFileActivitySeverityId",
    "EmailFileActivityStatusId",
    "EmailUrlActivity",
    "EmailUrlActivityActivityId",
    "EmailUrlActivitySeverityId",
    "EmailUrlActivityStatusId",
    "Endpoint",
    "EndpointConnection",
    "EndpointTypeId",
    "Enrichment",
    "Entity",
    "EntityManagement",
    "EntityManagementActivityId",
    "EntityManagementSeverityId",
    "EntityManagementStatusId",
    "Epss",
    "Evidences",
    "Extension",
    "Feature",
    "File",
    "FileActivity",
    "FileActivityActivityId",
    "FileActivitySeverityId",
    "FileActivityStatusId",
    "FileConfidentialityId",
    "FileHosting",
    "FileHostingActivityId",
    "FileHostingSeverityId",
    "FileHostingStatusId",
    "FileTypeId",
    "Finding",
    "FindingActivityId",
    "FindingConfidenceId",
    "FindingInfo",
    "FindingSeverityId",
    "FindingStatusId",
    "Fingerprint",
    "FingerprintAlgorithmId",
    "FirewallRule",
    "FtpActivity",
    "FtpActivityActivityId",
    "FtpActivitySeverityId",
    "FtpActivityStatusId",
    "Group",
    "GroupManagement",
    "GroupManagementActivityId",
    "GroupManagementSeverityId",
    "GroupManagementStatusId",
    "Hassh",
    "HttpActivity",
    "HttpActivityActivityId",
    "HttpActivitySeverityId",
    "HttpActivityStatusId",
    "HttpCookie",
    "HttpHeader",
    "HttpRequest",
    "HttpRequestHttpMethod",
    "HttpResponse",
    "IamSeverityId",
    "IamStatusId",
    "Idp",
    "Image",
    "IncidentFinding",
    "IncidentFindingActivityId",
    "IncidentFindingConfidenceId",
    "IncidentFindingImpactId",
    "IncidentFindingPriorityId",
    "IncidentFindingSeverityId",
    "IncidentFindingStatusId",
    "IncidentFindingVerdictId",
    "InventoryInfo",
    "InventoryInfoActivityId",
    "InventoryInfoSeverityId",
    "InventoryInfoStatusId",
    "Job",
    "JobRunStateId",
    "KbArticle",
    "Kernel",
    "KernelActivity",
    "KernelActivityActivityId",
    "KernelActivitySeverityId",
    "KernelActivityStatusId",
    "KernelDriver",
    "KernelExtension",
    "KernelExtensionActivityId",
    "KernelExtensionSeverityId",
    "KernelExtensionStatusId",
    "KernelTypeId",
    "KeyboardInfo",
    "KillChainPhase",
    "KillChainPhasePhaseId",
    "LdapPerson",
    "LoadBalancer",
    "Location",
    "Logger",
    "Malware",
    "MalwareClassificationIds",
    "ManagedEntity",
    "MemoryActivity",
    "MemoryActivityActivityId",
    "MemoryActivitySeverityId",
    "MemoryActivityStatusId",
    "Metadata",
    "Metric",
    "Module",
    "ModuleActivity",
    "ModuleActivityActivityId",
    "ModuleActivitySeverityId",
    "ModuleActivityStatusId",
    "ModuleLoadTypeId",
    "NetworkActivity",
    "NetworkActivitySeverityId",
    "NetworkActivityStatusId",
    "NetworkConnectionInfo",
    "NetworkConnectionInfoBoundaryId",
    "NetworkConnectionInfoDirectionId",
    "NetworkConnectionInfoProtocolVerId",
    "NetworkEndpoint",
    "NetworkEndpointTypeId",
    "NetworkFileActivity",
    "NetworkFileActivityActivityId",
    "NetworkFileActivitySeverityId",
    "NetworkFileActivityStatusId",
    "NetworkInterface",
    "NetworkInterfaceTypeId",
    "NetworkProxy",
    "NetworkProxyTypeId",
    "NetworkSeverityId",
    "NetworkStatusId",
    "NetworkTraffic",
    "NtpActivity",
    "NtpActivityActivityId",
    "NtpActivitySeverityId",
    "NtpActivityStatusId",
    "NtpActivityStratumId",
    "Object",
    "Observable",
    "ObservableTypeId",
    "Organization",
    "Os",
    "OsTypeId",
    "Package",
    "PatchState",
    "PatchStateActivityId",
    "PatchStateSeverityId",
    "PatchStateStatusId",
    "PeripheralDevice",
    "Policy",
    "Process",
    "ProcessActivity",
    "ProcessActivityActivityId",
    "ProcessActivityInjectionTypeId",
    "ProcessActivitySeverityId",
    "ProcessActivityStatusId",
    "ProcessIntegrityId",
    "Product",
    "QueryInfo",
    "RdpActivity",
    "RdpActivityActivityId",
    "RdpActivitySeverityId",
    "RdpActivityStatusId",
    "RelatedEvent",
    "Remediation",
    "Reputation",
    "ReputationScoreId",
    "Request",
    "Resource",
    "ResourceDetails",
    "Response",
    "RpcInterface",
    "Rule",
    "San",
    "Scan",
    "ScanActivity",
    "ScanActivityActivityId",
    "ScanActivitySeverityId",
    "ScanActivityStatusId",
    "ScanTypeId",
    "ScheduledJobActivity",
    "ScheduledJobActivityActivityId",
    "ScheduledJobActivitySeverityId",
    "ScheduledJobActivityStatusId",
    "SecurityFinding",
    "SecurityFindingActivityId",
    "SecurityFindingConfidenceId",
    "SecurityFindingImpactId",
    "SecurityFindingRiskLevelId",
    "SecurityFindingSeverityId",
    "SecurityFindingStateId",
    "SecurityFindingStatusId",
    "SecurityState",
    "SecurityStateStateId",
    "Service",
    "Session",
    "SmbActivity",
    "SmbActivityActivityId",
    "SmbActivitySeverityId",
    "SmbActivityShareTypeId",
    "SmbActivityStatusId",
    "SshActivity",
    "SshActivityAuthTypeId",
    "SshActivitySeverityId",
    "SshActivityStatusId",
    "SubTechnique",
    "SystemSeverityId",
    "SystemStatusId",
    "Table",
    "Tactic",
    "Technique",
    "Tls",
    "TlsExtension",
    "TlsExtensionTypeId",
    "Url",
    "UrlCategoryIds",
    "User",
    "UserAccess",
    "UserAccessActivityId",
    "UserAccessSeverityId",
    "UserAccessStatusId",
    "UserInventory",
    "UserInventoryActivityId",
    "UserInventorySeverityId",
    "UserInventoryStatusId",
    "UserTypeId",
    "Vulnerability",
    "VulnerabilityFinding",
    "VulnerabilityFindingActivityId",
    "VulnerabilityFindingConfidenceId",
    "VulnerabilityFindingSeverityId",
    "VulnerabilityFindingStatusId",
    "WebResource",
    "WebResourceAccessActivity",
    "WebResourceAccessActivityActivityId",
    "WebResourceAccessActivitySeverityId",
    "WebResourceAccessActivityStatusId",
    "WebResourcesActivity",
    "WebResourcesActivityActivityId",
    "WebResourcesActivitySeverityId",
    "WebResourcesActivityStatusId",
]

# Mapping of symbol names to their import paths
_IMPORT_MAP: dict[str, tuple[str, str]] = {
    "AccountChangeActivityId": ("ocsf.v1_1_0.enums", "AccountChangeActivityId"),
    "AccountChangeSeverityId": ("ocsf.v1_1_0.enums", "AccountChangeSeverityId"),
    "AccountChangeStatusId": ("ocsf.v1_1_0.enums", "AccountChangeStatusId"),
    "AccountTypeId": ("ocsf.v1_1_0.enums", "AccountTypeId"),
    "AnalyticTypeId": ("ocsf.v1_1_0.enums", "AnalyticTypeId"),
    "ApiActivityActivityId": ("ocsf.v1_1_0.enums", "ApiActivityActivityId"),
    "ApiActivitySeverityId": ("ocsf.v1_1_0.enums", "ApiActivitySeverityId"),
    "ApiActivityStatusId": ("ocsf.v1_1_0.enums", "ApiActivityStatusId"),
    "ApplicationLifecycleActivityId": ("ocsf.v1_1_0.enums", "ApplicationLifecycleActivityId"),
    "ApplicationLifecycleSeverityId": ("ocsf.v1_1_0.enums", "ApplicationLifecycleSeverityId"),
    "ApplicationLifecycleStatusId": ("ocsf.v1_1_0.enums", "ApplicationLifecycleStatusId"),
    "ApplicationSeverityId": ("ocsf.v1_1_0.enums", "ApplicationSeverityId"),
    "ApplicationStatusId": ("ocsf.v1_1_0.enums", "ApplicationStatusId"),
    "AuthenticationActivityId": ("ocsf.v1_1_0.enums", "AuthenticationActivityId"),
    "AuthenticationAuthProtocolId": ("ocsf.v1_1_0.enums", "AuthenticationAuthProtocolId"),
    "AuthenticationLogonTypeId": ("ocsf.v1_1_0.enums", "AuthenticationLogonTypeId"),
    "AuthenticationSeverityId": ("ocsf.v1_1_0.enums", "AuthenticationSeverityId"),
    "AuthenticationStatusId": ("ocsf.v1_1_0.enums", "AuthenticationStatusId"),
    "AuthorizeSessionActivityId": ("ocsf.v1_1_0.enums", "AuthorizeSessionActivityId"),
    "AuthorizeSessionSeverityId": ("ocsf.v1_1_0.enums", "AuthorizeSessionSeverityId"),
    "AuthorizeSessionStatusId": ("ocsf.v1_1_0.enums", "AuthorizeSessionStatusId"),
    "BaseEventSeverityId": ("ocsf.v1_1_0.enums", "BaseEventSeverityId"),
    "BaseEventStatusId": ("ocsf.v1_1_0.enums", "BaseEventStatusId"),
    "ComplianceFindingActivityId": ("ocsf.v1_1_0.enums", "ComplianceFindingActivityId"),
    "ComplianceFindingConfidenceId": ("ocsf.v1_1_0.enums", "ComplianceFindingConfidenceId"),
    "ComplianceFindingSeverityId": ("ocsf.v1_1_0.enums", "ComplianceFindingSeverityId"),
    "ComplianceFindingStatusId": ("ocsf.v1_1_0.enums", "ComplianceFindingStatusId"),
    "ComplianceStatusId": ("ocsf.v1_1_0.enums", "ComplianceStatusId"),
    "ConfigStateActivityId": ("ocsf.v1_1_0.enums", "ConfigStateActivityId"),
    "ConfigStateSeverityId": ("ocsf.v1_1_0.enums", "ConfigStateSeverityId"),
    "ConfigStateStatusId": ("ocsf.v1_1_0.enums", "ConfigStateStatusId"),
    "CvssDepth": ("ocsf.v1_1_0.enums", "CvssDepth"),
    "DatabaseTypeId": ("ocsf.v1_1_0.enums", "DatabaseTypeId"),
    "DatabucketTypeId": ("ocsf.v1_1_0.enums", "DatabucketTypeId"),
    "DatastoreActivityActivityId": ("ocsf.v1_1_0.enums", "DatastoreActivityActivityId"),
    "DatastoreActivitySeverityId": ("ocsf.v1_1_0.enums", "DatastoreActivitySeverityId"),
    "DatastoreActivityStatusId": ("ocsf.v1_1_0.enums", "DatastoreActivityStatusId"),
    "DatastoreActivityTypeId": ("ocsf.v1_1_0.enums", "DatastoreActivityTypeId"),
    "DetectionFindingActivityId": ("ocsf.v1_1_0.enums", "DetectionFindingActivityId"),
    "DetectionFindingConfidenceId": ("ocsf.v1_1_0.enums", "DetectionFindingConfidenceId"),
    "DetectionFindingImpactId": ("ocsf.v1_1_0.enums", "DetectionFindingImpactId"),
    "DetectionFindingRiskLevelId": ("ocsf.v1_1_0.enums", "DetectionFindingRiskLevelId"),
    "DetectionFindingSeverityId": ("ocsf.v1_1_0.enums", "DetectionFindingSeverityId"),
    "DetectionFindingStatusId": ("ocsf.v1_1_0.enums", "DetectionFindingStatusId"),
    "DeviceConfigStateChangeActivityId": ("ocsf.v1_1_0.enums", "DeviceConfigStateChangeActivityId"),
    "DeviceConfigStateChangePrevSecurityLevelId": (
        "ocsf.v1_1_0.enums",
        "DeviceConfigStateChangePrevSecurityLevelId",
    ),
    "DeviceConfigStateChangeSecurityLevelId": (
        "ocsf.v1_1_0.enums",
        "DeviceConfigStateChangeSecurityLevelId",
    ),
    "DeviceConfigStateChangeSeverityId": ("ocsf.v1_1_0.enums", "DeviceConfigStateChangeSeverityId"),
    "DeviceConfigStateChangeStatusId": ("ocsf.v1_1_0.enums", "DeviceConfigStateChangeStatusId"),
    "DeviceRiskLevelId": ("ocsf.v1_1_0.enums", "DeviceRiskLevelId"),
    "DeviceTypeId": ("ocsf.v1_1_0.enums", "DeviceTypeId"),
    "DhcpActivityActivityId": ("ocsf.v1_1_0.enums", "DhcpActivityActivityId"),
    "DhcpActivitySeverityId": ("ocsf.v1_1_0.enums", "DhcpActivitySeverityId"),
    "DhcpActivityStatusId": ("ocsf.v1_1_0.enums", "DhcpActivityStatusId"),
    "DigitalSignatureAlgorithmId": ("ocsf.v1_1_0.enums", "DigitalSignatureAlgorithmId"),
    "DiscoveryActivityId": ("ocsf.v1_1_0.enums", "DiscoveryActivityId"),
    "DiscoveryResultActivityId": ("ocsf.v1_1_0.enums", "DiscoveryResultActivityId"),
    "DiscoveryResultSeverityId": ("ocsf.v1_1_0.enums", "DiscoveryResultSeverityId"),
    "DiscoveryResultStatusId": ("ocsf.v1_1_0.enums", "DiscoveryResultStatusId"),
    "DiscoverySeverityId": ("ocsf.v1_1_0.enums", "DiscoverySeverityId"),
    "DiscoveryStatusId": ("ocsf.v1_1_0.enums", "DiscoveryStatusId"),
    "DnsActivityActivityId": ("ocsf.v1_1_0.enums", "DnsActivityActivityId"),
    "DnsActivityRcodeId": ("ocsf.v1_1_0.enums", "DnsActivityRcodeId"),
    "DnsActivitySeverityId": ("ocsf.v1_1_0.enums", "DnsActivitySeverityId"),
    "DnsActivityStatusId": ("ocsf.v1_1_0.enums", "DnsActivityStatusId"),
    "DnsAnswerFlagIds": ("ocsf.v1_1_0.enums", "DnsAnswerFlagIds"),
    "DnsQueryOpcodeId": ("ocsf.v1_1_0.enums", "DnsQueryOpcodeId"),
    "EmailActivityActivityId": ("ocsf.v1_1_0.enums", "EmailActivityActivityId"),
    "EmailActivityDirectionId": ("ocsf.v1_1_0.enums", "EmailActivityDirectionId"),
    "EmailActivitySeverityId": ("ocsf.v1_1_0.enums", "EmailActivitySeverityId"),
    "EmailActivityStatusId": ("ocsf.v1_1_0.enums", "EmailActivityStatusId"),
    "EmailFileActivityActivityId": ("ocsf.v1_1_0.enums", "EmailFileActivityActivityId"),
    "EmailFileActivitySeverityId": ("ocsf.v1_1_0.enums", "EmailFileActivitySeverityId"),
    "EmailFileActivityStatusId": ("ocsf.v1_1_0.enums", "EmailFileActivityStatusId"),
    "EmailUrlActivityActivityId": ("ocsf.v1_1_0.enums", "EmailUrlActivityActivityId"),
    "EmailUrlActivitySeverityId": ("ocsf.v1_1_0.enums", "EmailUrlActivitySeverityId"),
    "EmailUrlActivityStatusId": ("ocsf.v1_1_0.enums", "EmailUrlActivityStatusId"),
    "EndpointTypeId": ("ocsf.v1_1_0.enums", "EndpointTypeId"),
    "EntityManagementActivityId": ("ocsf.v1_1_0.enums", "EntityManagementActivityId"),
    "EntityManagementSeverityId": ("ocsf.v1_1_0.enums", "EntityManagementSeverityId"),
    "EntityManagementStatusId": ("ocsf.v1_1_0.enums", "EntityManagementStatusId"),
    "FileActivityActivityId": ("ocsf.v1_1_0.enums", "FileActivityActivityId"),
    "FileActivitySeverityId": ("ocsf.v1_1_0.enums", "FileActivitySeverityId"),
    "FileActivityStatusId": ("ocsf.v1_1_0.enums", "FileActivityStatusId"),
    "FileConfidentialityId": ("ocsf.v1_1_0.enums", "FileConfidentialityId"),
    "FileHostingActivityId": ("ocsf.v1_1_0.enums", "FileHostingActivityId"),
    "FileHostingSeverityId": ("ocsf.v1_1_0.enums", "FileHostingSeverityId"),
    "FileHostingStatusId": ("ocsf.v1_1_0.enums", "FileHostingStatusId"),
    "FileTypeId": ("ocsf.v1_1_0.enums", "FileTypeId"),
    "FindingActivityId": ("ocsf.v1_1_0.enums", "FindingActivityId"),
    "FindingConfidenceId": ("ocsf.v1_1_0.enums", "FindingConfidenceId"),
    "FindingSeverityId": ("ocsf.v1_1_0.enums", "FindingSeverityId"),
    "FindingStatusId": ("ocsf.v1_1_0.enums", "FindingStatusId"),
    "FingerprintAlgorithmId": ("ocsf.v1_1_0.enums", "FingerprintAlgorithmId"),
    "FtpActivityActivityId": ("ocsf.v1_1_0.enums", "FtpActivityActivityId"),
    "FtpActivitySeverityId": ("ocsf.v1_1_0.enums", "FtpActivitySeverityId"),
    "FtpActivityStatusId": ("ocsf.v1_1_0.enums", "FtpActivityStatusId"),
    "GroupManagementActivityId": ("ocsf.v1_1_0.enums", "GroupManagementActivityId"),
    "GroupManagementSeverityId": ("ocsf.v1_1_0.enums", "GroupManagementSeverityId"),
    "GroupManagementStatusId": ("ocsf.v1_1_0.enums", "GroupManagementStatusId"),
    "HttpActivityActivityId": ("ocsf.v1_1_0.enums", "HttpActivityActivityId"),
    "HttpActivitySeverityId": ("ocsf.v1_1_0.enums", "HttpActivitySeverityId"),
    "HttpActivityStatusId": ("ocsf.v1_1_0.enums", "HttpActivityStatusId"),
    "HttpRequestHttpMethod": ("ocsf.v1_1_0.enums", "HttpRequestHttpMethod"),
    "IamSeverityId": ("ocsf.v1_1_0.enums", "IamSeverityId"),
    "IamStatusId": ("ocsf.v1_1_0.enums", "IamStatusId"),
    "IncidentFindingActivityId": ("ocsf.v1_1_0.enums", "IncidentFindingActivityId"),
    "IncidentFindingConfidenceId": ("ocsf.v1_1_0.enums", "IncidentFindingConfidenceId"),
    "IncidentFindingImpactId": ("ocsf.v1_1_0.enums", "IncidentFindingImpactId"),
    "IncidentFindingPriorityId": ("ocsf.v1_1_0.enums", "IncidentFindingPriorityId"),
    "IncidentFindingSeverityId": ("ocsf.v1_1_0.enums", "IncidentFindingSeverityId"),
    "IncidentFindingStatusId": ("ocsf.v1_1_0.enums", "IncidentFindingStatusId"),
    "IncidentFindingVerdictId": ("ocsf.v1_1_0.enums", "IncidentFindingVerdictId"),
    "InventoryInfoActivityId": ("ocsf.v1_1_0.enums", "InventoryInfoActivityId"),
    "InventoryInfoSeverityId": ("ocsf.v1_1_0.enums", "InventoryInfoSeverityId"),
    "InventoryInfoStatusId": ("ocsf.v1_1_0.enums", "InventoryInfoStatusId"),
    "JobRunStateId": ("ocsf.v1_1_0.enums", "JobRunStateId"),
    "KernelActivityActivityId": ("ocsf.v1_1_0.enums", "KernelActivityActivityId"),
    "KernelActivitySeverityId": ("ocsf.v1_1_0.enums", "KernelActivitySeverityId"),
    "KernelActivityStatusId": ("ocsf.v1_1_0.enums", "KernelActivityStatusId"),
    "KernelExtensionActivityId": ("ocsf.v1_1_0.enums", "KernelExtensionActivityId"),
    "KernelExtensionSeverityId": ("ocsf.v1_1_0.enums", "KernelExtensionSeverityId"),
    "KernelExtensionStatusId": ("ocsf.v1_1_0.enums", "KernelExtensionStatusId"),
    "KernelTypeId": ("ocsf.v1_1_0.enums", "KernelTypeId"),
    "KillChainPhasePhaseId": ("ocsf.v1_1_0.enums", "KillChainPhasePhaseId"),
    "MalwareClassificationIds": ("ocsf.v1_1_0.enums", "MalwareClassificationIds"),
    "MemoryActivityActivityId": ("ocsf.v1_1_0.enums", "MemoryActivityActivityId"),
    "MemoryActivitySeverityId": ("ocsf.v1_1_0.enums", "MemoryActivitySeverityId"),
    "MemoryActivityStatusId": ("ocsf.v1_1_0.enums", "MemoryActivityStatusId"),
    "ModuleActivityActivityId": ("ocsf.v1_1_0.enums", "ModuleActivityActivityId"),
    "ModuleActivitySeverityId": ("ocsf.v1_1_0.enums", "ModuleActivitySeverityId"),
    "ModuleActivityStatusId": ("ocsf.v1_1_0.enums", "ModuleActivityStatusId"),
    "ModuleLoadTypeId": ("ocsf.v1_1_0.enums", "ModuleLoadTypeId"),
    "NetworkActivitySeverityId": ("ocsf.v1_1_0.enums", "NetworkActivitySeverityId"),
    "NetworkActivityStatusId": ("ocsf.v1_1_0.enums", "NetworkActivityStatusId"),
    "NetworkConnectionInfoBoundaryId": ("ocsf.v1_1_0.enums", "NetworkConnectionInfoBoundaryId"),
    "NetworkConnectionInfoDirectionId": ("ocsf.v1_1_0.enums", "NetworkConnectionInfoDirectionId"),
    "NetworkConnectionInfoProtocolVerId": (
        "ocsf.v1_1_0.enums",
        "NetworkConnectionInfoProtocolVerId",
    ),
    "NetworkEndpointTypeId": ("ocsf.v1_1_0.enums", "NetworkEndpointTypeId"),
    "NetworkFileActivityActivityId": ("ocsf.v1_1_0.enums", "NetworkFileActivityActivityId"),
    "NetworkFileActivitySeverityId": ("ocsf.v1_1_0.enums", "NetworkFileActivitySeverityId"),
    "NetworkFileActivityStatusId": ("ocsf.v1_1_0.enums", "NetworkFileActivityStatusId"),
    "NetworkInterfaceTypeId": ("ocsf.v1_1_0.enums", "NetworkInterfaceTypeId"),
    "NetworkProxyTypeId": ("ocsf.v1_1_0.enums", "NetworkProxyTypeId"),
    "NetworkSeverityId": ("ocsf.v1_1_0.enums", "NetworkSeverityId"),
    "NetworkStatusId": ("ocsf.v1_1_0.enums", "NetworkStatusId"),
    "NtpActivityActivityId": ("ocsf.v1_1_0.enums", "NtpActivityActivityId"),
    "NtpActivitySeverityId": ("ocsf.v1_1_0.enums", "NtpActivitySeverityId"),
    "NtpActivityStatusId": ("ocsf.v1_1_0.enums", "NtpActivityStatusId"),
    "NtpActivityStratumId": ("ocsf.v1_1_0.enums", "NtpActivityStratumId"),
    "ObservableTypeId": ("ocsf.v1_1_0.enums", "ObservableTypeId"),
    "OsTypeId": ("ocsf.v1_1_0.enums", "OsTypeId"),
    "PatchStateActivityId": ("ocsf.v1_1_0.enums", "PatchStateActivityId"),
    "PatchStateSeverityId": ("ocsf.v1_1_0.enums", "PatchStateSeverityId"),
    "PatchStateStatusId": ("ocsf.v1_1_0.enums", "PatchStateStatusId"),
    "ProcessActivityActivityId": ("ocsf.v1_1_0.enums", "ProcessActivityActivityId"),
    "ProcessActivityInjectionTypeId": ("ocsf.v1_1_0.enums", "ProcessActivityInjectionTypeId"),
    "ProcessActivitySeverityId": ("ocsf.v1_1_0.enums", "ProcessActivitySeverityId"),
    "ProcessActivityStatusId": ("ocsf.v1_1_0.enums", "ProcessActivityStatusId"),
    "ProcessIntegrityId": ("ocsf.v1_1_0.enums", "ProcessIntegrityId"),
    "RdpActivityActivityId": ("ocsf.v1_1_0.enums", "RdpActivityActivityId"),
    "RdpActivitySeverityId": ("ocsf.v1_1_0.enums", "RdpActivitySeverityId"),
    "RdpActivityStatusId": ("ocsf.v1_1_0.enums", "RdpActivityStatusId"),
    "ReputationScoreId": ("ocsf.v1_1_0.enums", "ReputationScoreId"),
    "ScanActivityActivityId": ("ocsf.v1_1_0.enums", "ScanActivityActivityId"),
    "ScanActivitySeverityId": ("ocsf.v1_1_0.enums", "ScanActivitySeverityId"),
    "ScanActivityStatusId": ("ocsf.v1_1_0.enums", "ScanActivityStatusId"),
    "ScanTypeId": ("ocsf.v1_1_0.enums", "ScanTypeId"),
    "ScheduledJobActivityActivityId": ("ocsf.v1_1_0.enums", "ScheduledJobActivityActivityId"),
    "ScheduledJobActivitySeverityId": ("ocsf.v1_1_0.enums", "ScheduledJobActivitySeverityId"),
    "ScheduledJobActivityStatusId": ("ocsf.v1_1_0.enums", "ScheduledJobActivityStatusId"),
    "SecurityFindingActivityId": ("ocsf.v1_1_0.enums", "SecurityFindingActivityId"),
    "SecurityFindingConfidenceId": ("ocsf.v1_1_0.enums", "SecurityFindingConfidenceId"),
    "SecurityFindingImpactId": ("ocsf.v1_1_0.enums", "SecurityFindingImpactId"),
    "SecurityFindingRiskLevelId": ("ocsf.v1_1_0.enums", "SecurityFindingRiskLevelId"),
    "SecurityFindingSeverityId": ("ocsf.v1_1_0.enums", "SecurityFindingSeverityId"),
    "SecurityFindingStateId": ("ocsf.v1_1_0.enums", "SecurityFindingStateId"),
    "SecurityFindingStatusId": ("ocsf.v1_1_0.enums", "SecurityFindingStatusId"),
    "SecurityStateStateId": ("ocsf.v1_1_0.enums", "SecurityStateStateId"),
    "SmbActivityActivityId": ("ocsf.v1_1_0.enums", "SmbActivityActivityId"),
    "SmbActivitySeverityId": ("ocsf.v1_1_0.enums", "SmbActivitySeverityId"),
    "SmbActivityShareTypeId": ("ocsf.v1_1_0.enums", "SmbActivityShareTypeId"),
    "SmbActivityStatusId": ("ocsf.v1_1_0.enums", "SmbActivityStatusId"),
    "SshActivityAuthTypeId": ("ocsf.v1_1_0.enums", "SshActivityAuthTypeId"),
    "SshActivitySeverityId": ("ocsf.v1_1_0.enums", "SshActivitySeverityId"),
    "SshActivityStatusId": ("ocsf.v1_1_0.enums", "SshActivityStatusId"),
    "SystemSeverityId": ("ocsf.v1_1_0.enums", "SystemSeverityId"),
    "SystemStatusId": ("ocsf.v1_1_0.enums", "SystemStatusId"),
    "TlsExtensionTypeId": ("ocsf.v1_1_0.enums", "TlsExtensionTypeId"),
    "UrlCategoryIds": ("ocsf.v1_1_0.enums", "UrlCategoryIds"),
    "UserAccessActivityId": ("ocsf.v1_1_0.enums", "UserAccessActivityId"),
    "UserAccessSeverityId": ("ocsf.v1_1_0.enums", "UserAccessSeverityId"),
    "UserAccessStatusId": ("ocsf.v1_1_0.enums", "UserAccessStatusId"),
    "UserInventoryActivityId": ("ocsf.v1_1_0.enums", "UserInventoryActivityId"),
    "UserInventorySeverityId": ("ocsf.v1_1_0.enums", "UserInventorySeverityId"),
    "UserInventoryStatusId": ("ocsf.v1_1_0.enums", "UserInventoryStatusId"),
    "UserTypeId": ("ocsf.v1_1_0.enums", "UserTypeId"),
    "VulnerabilityFindingActivityId": ("ocsf.v1_1_0.enums", "VulnerabilityFindingActivityId"),
    "VulnerabilityFindingConfidenceId": ("ocsf.v1_1_0.enums", "VulnerabilityFindingConfidenceId"),
    "VulnerabilityFindingSeverityId": ("ocsf.v1_1_0.enums", "VulnerabilityFindingSeverityId"),
    "VulnerabilityFindingStatusId": ("ocsf.v1_1_0.enums", "VulnerabilityFindingStatusId"),
    "WebResourceAccessActivityActivityId": (
        "ocsf.v1_1_0.enums",
        "WebResourceAccessActivityActivityId",
    ),
    "WebResourceAccessActivitySeverityId": (
        "ocsf.v1_1_0.enums",
        "WebResourceAccessActivitySeverityId",
    ),
    "WebResourceAccessActivityStatusId": ("ocsf.v1_1_0.enums", "WebResourceAccessActivityStatusId"),
    "WebResourcesActivityActivityId": ("ocsf.v1_1_0.enums", "WebResourcesActivityActivityId"),
    "WebResourcesActivitySeverityId": ("ocsf.v1_1_0.enums", "WebResourcesActivitySeverityId"),
    "WebResourcesActivityStatusId": ("ocsf.v1_1_0.enums", "WebResourcesActivityStatusId"),
    "Account": ("ocsf.v1_1_0.objects", "Account"),
    "Actor": ("ocsf.v1_1_0.objects", "Actor"),
    "AffectedCode": ("ocsf.v1_1_0.objects", "AffectedCode"),
    "AffectedPackage": ("ocsf.v1_1_0.objects", "AffectedPackage"),
    "Analytic": ("ocsf.v1_1_0.objects", "Analytic"),
    "Api": ("ocsf.v1_1_0.objects", "Api"),
    "Attack": ("ocsf.v1_1_0.objects", "Attack"),
    "Authorization": ("ocsf.v1_1_0.objects", "Authorization"),
    "Certificate": ("ocsf.v1_1_0.objects", "Certificate"),
    "CisBenchmark": ("ocsf.v1_1_0.objects", "CisBenchmark"),
    "CisBenchmarkResult": ("ocsf.v1_1_0.objects", "CisBenchmarkResult"),
    "CisControl": ("ocsf.v1_1_0.objects", "CisControl"),
    "CisCsc": ("ocsf.v1_1_0.objects", "CisCsc"),
    "Cloud": ("ocsf.v1_1_0.objects", "Cloud"),
    "Compliance": ("ocsf.v1_1_0.objects", "Compliance"),
    "Container": ("ocsf.v1_1_0.objects", "Container"),
    "Cve": ("ocsf.v1_1_0.objects", "Cve"),
    "Cvss": ("ocsf.v1_1_0.objects", "Cvss"),
    "Cwe": ("ocsf.v1_1_0.objects", "Cwe"),
    "Database": ("ocsf.v1_1_0.objects", "Database"),
    "Databucket": ("ocsf.v1_1_0.objects", "Databucket"),
    "DceRpc": ("ocsf.v1_1_0.objects", "DceRpc"),
    "Device": ("ocsf.v1_1_0.objects", "Device"),
    "DeviceHwInfo": ("ocsf.v1_1_0.objects", "DeviceHwInfo"),
    "DigitalSignature": ("ocsf.v1_1_0.objects", "DigitalSignature"),
    "Display": ("ocsf.v1_1_0.objects", "Display"),
    "Dns": ("ocsf.v1_1_0.objects", "Dns"),
    "DnsAnswer": ("ocsf.v1_1_0.objects", "DnsAnswer"),
    "DnsQuery": ("ocsf.v1_1_0.objects", "DnsQuery"),
    "Email": ("ocsf.v1_1_0.objects", "Email"),
    "EmailAuth": ("ocsf.v1_1_0.objects", "EmailAuth"),
    "Endpoint": ("ocsf.v1_1_0.objects", "Endpoint"),
    "EndpointConnection": ("ocsf.v1_1_0.objects", "EndpointConnection"),
    "Enrichment": ("ocsf.v1_1_0.objects", "Enrichment"),
    "Entity": ("ocsf.v1_1_0.objects", "Entity"),
    "Epss": ("ocsf.v1_1_0.objects", "Epss"),
    "Evidences": ("ocsf.v1_1_0.objects", "Evidences"),
    "Extension": ("ocsf.v1_1_0.objects", "Extension"),
    "Feature": ("ocsf.v1_1_0.objects", "Feature"),
    "File": ("ocsf.v1_1_0.objects", "File"),
    "Finding": ("ocsf.v1_1_0.objects", "Finding"),
    "FindingInfo": ("ocsf.v1_1_0.objects", "FindingInfo"),
    "Fingerprint": ("ocsf.v1_1_0.objects", "Fingerprint"),
    "FirewallRule": ("ocsf.v1_1_0.objects", "FirewallRule"),
    "Group": ("ocsf.v1_1_0.objects", "Group"),
    "Hassh": ("ocsf.v1_1_0.objects", "Hassh"),
    "HttpCookie": ("ocsf.v1_1_0.objects", "HttpCookie"),
    "HttpHeader": ("ocsf.v1_1_0.objects", "HttpHeader"),
    "HttpRequest": ("ocsf.v1_1_0.objects", "HttpRequest"),
    "HttpResponse": ("ocsf.v1_1_0.objects", "HttpResponse"),
    "Idp": ("ocsf.v1_1_0.objects", "Idp"),
    "Image": ("ocsf.v1_1_0.objects", "Image"),
    "Job": ("ocsf.v1_1_0.objects", "Job"),
    "KbArticle": ("ocsf.v1_1_0.objects", "KbArticle"),
    "Kernel": ("ocsf.v1_1_0.objects", "Kernel"),
    "KernelDriver": ("ocsf.v1_1_0.objects", "KernelDriver"),
    "KeyboardInfo": ("ocsf.v1_1_0.objects", "KeyboardInfo"),
    "KillChainPhase": ("ocsf.v1_1_0.objects", "KillChainPhase"),
    "LdapPerson": ("ocsf.v1_1_0.objects", "LdapPerson"),
    "LoadBalancer": ("ocsf.v1_1_0.objects", "LoadBalancer"),
    "Location": ("ocsf.v1_1_0.objects", "Location"),
    "Logger": ("ocsf.v1_1_0.objects", "Logger"),
    "Malware": ("ocsf.v1_1_0.objects", "Malware"),
    "ManagedEntity": ("ocsf.v1_1_0.objects", "ManagedEntity"),
    "Metadata": ("ocsf.v1_1_0.objects", "Metadata"),
    "Metric": ("ocsf.v1_1_0.objects", "Metric"),
    "Module": ("ocsf.v1_1_0.objects", "Module"),
    "NetworkConnectionInfo": ("ocsf.v1_1_0.objects", "NetworkConnectionInfo"),
    "NetworkEndpoint": ("ocsf.v1_1_0.objects", "NetworkEndpoint"),
    "NetworkInterface": ("ocsf.v1_1_0.objects", "NetworkInterface"),
    "NetworkProxy": ("ocsf.v1_1_0.objects", "NetworkProxy"),
    "NetworkTraffic": ("ocsf.v1_1_0.objects", "NetworkTraffic"),
    "Object": ("ocsf.v1_1_0.objects", "Object"),
    "Observable": ("ocsf.v1_1_0.objects", "Observable"),
    "Organization": ("ocsf.v1_1_0.objects", "Organization"),
    "Os": ("ocsf.v1_1_0.objects", "Os"),
    "Package": ("ocsf.v1_1_0.objects", "Package"),
    "PeripheralDevice": ("ocsf.v1_1_0.objects", "PeripheralDevice"),
    "Policy": ("ocsf.v1_1_0.objects", "Policy"),
    "Process": ("ocsf.v1_1_0.objects", "Process"),
    "Product": ("ocsf.v1_1_0.objects", "Product"),
    "QueryInfo": ("ocsf.v1_1_0.objects", "QueryInfo"),
    "RelatedEvent": ("ocsf.v1_1_0.objects", "RelatedEvent"),
    "Remediation": ("ocsf.v1_1_0.objects", "Remediation"),
    "Reputation": ("ocsf.v1_1_0.objects", "Reputation"),
    "Request": ("ocsf.v1_1_0.objects", "Request"),
    "Resource": ("ocsf.v1_1_0.objects", "Resource"),
    "ResourceDetails": ("ocsf.v1_1_0.objects", "ResourceDetails"),
    "Response": ("ocsf.v1_1_0.objects", "Response"),
    "RpcInterface": ("ocsf.v1_1_0.objects", "RpcInterface"),
    "Rule": ("ocsf.v1_1_0.objects", "Rule"),
    "San": ("ocsf.v1_1_0.objects", "San"),
    "Scan": ("ocsf.v1_1_0.objects", "Scan"),
    "SecurityState": ("ocsf.v1_1_0.objects", "SecurityState"),
    "Service": ("ocsf.v1_1_0.objects", "Service"),
    "Session": ("ocsf.v1_1_0.objects", "Session"),
    "SubTechnique": ("ocsf.v1_1_0.objects", "SubTechnique"),
    "Table": ("ocsf.v1_1_0.objects", "Table"),
    "Tactic": ("ocsf.v1_1_0.objects", "Tactic"),
    "Technique": ("ocsf.v1_1_0.objects", "Technique"),
    "Tls": ("ocsf.v1_1_0.objects", "Tls"),
    "TlsExtension": ("ocsf.v1_1_0.objects", "TlsExtension"),
    "Url": ("ocsf.v1_1_0.objects", "Url"),
    "User": ("ocsf.v1_1_0.objects", "User"),
    "Vulnerability": ("ocsf.v1_1_0.objects", "Vulnerability"),
    "WebResource": ("ocsf.v1_1_0.objects", "WebResource"),
    "AccountChange": ("ocsf.v1_1_0.events", "AccountChange"),
    "ApiActivity": ("ocsf.v1_1_0.events", "ApiActivity"),
    "ApplicationLifecycle": ("ocsf.v1_1_0.events", "ApplicationLifecycle"),
    "Authentication": ("ocsf.v1_1_0.events", "Authentication"),
    "AuthorizeSession": ("ocsf.v1_1_0.events", "AuthorizeSession"),
    "ComplianceFinding": ("ocsf.v1_1_0.events", "ComplianceFinding"),
    "ConfigState": ("ocsf.v1_1_0.events", "ConfigState"),
    "DatastoreActivity": ("ocsf.v1_1_0.events", "DatastoreActivity"),
    "DetectionFinding": ("ocsf.v1_1_0.events", "DetectionFinding"),
    "DeviceConfigStateChange": ("ocsf.v1_1_0.events", "DeviceConfigStateChange"),
    "DhcpActivity": ("ocsf.v1_1_0.events", "DhcpActivity"),
    "DnsActivity": ("ocsf.v1_1_0.events", "DnsActivity"),
    "EmailActivity": ("ocsf.v1_1_0.events", "EmailActivity"),
    "EmailFileActivity": ("ocsf.v1_1_0.events", "EmailFileActivity"),
    "EmailUrlActivity": ("ocsf.v1_1_0.events", "EmailUrlActivity"),
    "EntityManagement": ("ocsf.v1_1_0.events", "EntityManagement"),
    "FileActivity": ("ocsf.v1_1_0.events", "FileActivity"),
    "FileHosting": ("ocsf.v1_1_0.events", "FileHosting"),
    "FtpActivity": ("ocsf.v1_1_0.events", "FtpActivity"),
    "GroupManagement": ("ocsf.v1_1_0.events", "GroupManagement"),
    "HttpActivity": ("ocsf.v1_1_0.events", "HttpActivity"),
    "IncidentFinding": ("ocsf.v1_1_0.events", "IncidentFinding"),
    "InventoryInfo": ("ocsf.v1_1_0.events", "InventoryInfo"),
    "KernelActivity": ("ocsf.v1_1_0.events", "KernelActivity"),
    "KernelExtension": ("ocsf.v1_1_0.events", "KernelExtension"),
    "MemoryActivity": ("ocsf.v1_1_0.events", "MemoryActivity"),
    "ModuleActivity": ("ocsf.v1_1_0.events", "ModuleActivity"),
    "NetworkActivity": ("ocsf.v1_1_0.events", "NetworkActivity"),
    "NetworkFileActivity": ("ocsf.v1_1_0.events", "NetworkFileActivity"),
    "NtpActivity": ("ocsf.v1_1_0.events", "NtpActivity"),
    "PatchState": ("ocsf.v1_1_0.events", "PatchState"),
    "ProcessActivity": ("ocsf.v1_1_0.events", "ProcessActivity"),
    "RdpActivity": ("ocsf.v1_1_0.events", "RdpActivity"),
    "ScanActivity": ("ocsf.v1_1_0.events", "ScanActivity"),
    "ScheduledJobActivity": ("ocsf.v1_1_0.events", "ScheduledJobActivity"),
    "SecurityFinding": ("ocsf.v1_1_0.events", "SecurityFinding"),
    "SmbActivity": ("ocsf.v1_1_0.events", "SmbActivity"),
    "SshActivity": ("ocsf.v1_1_0.events", "SshActivity"),
    "UserAccess": ("ocsf.v1_1_0.events", "UserAccess"),
    "UserInventory": ("ocsf.v1_1_0.events", "UserInventory"),
    "VulnerabilityFinding": ("ocsf.v1_1_0.events", "VulnerabilityFinding"),
    "WebResourceAccessActivity": ("ocsf.v1_1_0.events", "WebResourceAccessActivity"),
    "WebResourcesActivity": ("ocsf.v1_1_0.events", "WebResourcesActivity"),
}

# Track which models need rebuilding after import
_MODELS_TO_REBUILD = {
    "Account",
    "Actor",
    "AffectedCode",
    "AffectedPackage",
    "Analytic",
    "Api",
    "Attack",
    "Authorization",
    "Certificate",
    "CisBenchmark",
    "CisBenchmarkResult",
    "CisControl",
    "CisCsc",
    "Cloud",
    "Compliance",
    "Container",
    "Cve",
    "Cvss",
    "Cwe",
    "Database",
    "Databucket",
    "DceRpc",
    "Device",
    "DeviceHwInfo",
    "DigitalSignature",
    "Display",
    "Dns",
    "DnsAnswer",
    "DnsQuery",
    "Email",
    "EmailAuth",
    "Endpoint",
    "EndpointConnection",
    "Enrichment",
    "Entity",
    "Epss",
    "Evidences",
    "Extension",
    "Feature",
    "File",
    "Finding",
    "FindingInfo",
    "Fingerprint",
    "FirewallRule",
    "Group",
    "Hassh",
    "HttpCookie",
    "HttpHeader",
    "HttpRequest",
    "HttpResponse",
    "Idp",
    "Image",
    "Job",
    "KbArticle",
    "Kernel",
    "KernelDriver",
    "KeyboardInfo",
    "KillChainPhase",
    "LdapPerson",
    "LoadBalancer",
    "Location",
    "Logger",
    "Malware",
    "ManagedEntity",
    "Metadata",
    "Metric",
    "Module",
    "NetworkConnectionInfo",
    "NetworkEndpoint",
    "NetworkInterface",
    "NetworkProxy",
    "NetworkTraffic",
    "Object",
    "Observable",
    "Organization",
    "Os",
    "Package",
    "PeripheralDevice",
    "Policy",
    "Process",
    "Product",
    "QueryInfo",
    "RelatedEvent",
    "Remediation",
    "Reputation",
    "Request",
    "Resource",
    "ResourceDetails",
    "Response",
    "RpcInterface",
    "Rule",
    "San",
    "Scan",
    "SecurityState",
    "Service",
    "Session",
    "SubTechnique",
    "Table",
    "Tactic",
    "Technique",
    "Tls",
    "TlsExtension",
    "Url",
    "User",
    "Vulnerability",
    "WebResource",
    "AccountChange",
    "ApiActivity",
    "ApplicationLifecycle",
    "Authentication",
    "AuthorizeSession",
    "ComplianceFinding",
    "ConfigState",
    "DatastoreActivity",
    "DetectionFinding",
    "DeviceConfigStateChange",
    "DhcpActivity",
    "DnsActivity",
    "EmailActivity",
    "EmailFileActivity",
    "EmailUrlActivity",
    "EntityManagement",
    "FileActivity",
    "FileHosting",
    "FtpActivity",
    "GroupManagement",
    "HttpActivity",
    "IncidentFinding",
    "InventoryInfo",
    "KernelActivity",
    "KernelExtension",
    "MemoryActivity",
    "ModuleActivity",
    "NetworkActivity",
    "NetworkFileActivity",
    "NtpActivity",
    "PatchState",
    "ProcessActivity",
    "RdpActivity",
    "ScanActivity",
    "ScheduledJobActivity",
    "SecurityFinding",
    "SmbActivity",
    "SshActivity",
    "UserAccess",
    "UserInventory",
    "VulnerabilityFinding",
    "WebResourceAccessActivity",
    "WebResourcesActivity",
}

# Track what's been imported and whether all models have been rebuilt
_imported: set[str] = set()
_all_models_rebuilt = False


def _rebuild_all_models() -> None:
    """Import and rebuild all models when first model is accessed.

    This also imports all enums to ensure they're available for model references.
    """
    global _all_models_rebuilt
    if _all_models_rebuilt:
        return

    # Import all symbols (enums and models) first
    for name in _IMPORT_MAP:
        if name not in _imported:
            module_path, module_name = _IMPORT_MAP[name]
            module = __import__(module_path, fromlist=[module_name])
            symbol = getattr(module, module_name)
            globals()[name] = symbol
            _imported.add(name)

    # Now rebuild all models with complete namespace
    _globals = sys.modules[__name__].__dict__
    for model_name in _MODELS_TO_REBUILD:
        globals()[model_name].model_rebuild(_types_namespace=_globals)

    _all_models_rebuilt = True


def __getattr__(name: str) -> Any:
    """Lazy import symbols on first access."""
    if name not in _IMPORT_MAP:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    # Check if already imported
    if name in _imported:
        return globals()[name]

    # If this is a model and models haven't been rebuilt yet, do batch rebuild
    if name in _MODELS_TO_REBUILD and not _all_models_rebuilt:
        _rebuild_all_models()
        return globals()[name]

    # Import non-model symbols (enums) normally
    module_path, module_name = _IMPORT_MAP[name]
    module = __import__(module_path, fromlist=[module_name])
    symbol = getattr(module, module_name)

    # Cache in module globals
    globals()[name] = symbol
    _imported.add(name)

    return symbol


def __dir__() -> list[str]:
    """Support for dir() and autocomplete."""
    return sorted(__all__)
